### ISSUE TITLE
GetX

### ISSUE THREAD

**Issue by paulocagol** [flutterdata/flutter_data#101]
Hello, is there any implementation/integration with GetX?

I would like some example if possible, as it exists today with Provider and Reverpod.

Thanks.

**Comment by frank06** [comment]
Hi! Sorry, I don't have

**Comment by frank06** [comment]
Here's a pure Dart small example: https://github.com/flutterdata/flutter_data/blob/master/example/lib/main.dart

You can use that to integrate it to other tools

**Comment by paulocagol** [comment]
Okay, no problem, I will evaluate the example.

Thanks for the package!

**Comment by sawirricardo** [comment]
Hi @paulocagol can you share your findings? Thank you
