### ISSUE TITLE
The method 'xxx' isn't defined for the type 'Repository'

### ISSUE THREAD

**Issue by rubgithub** [flutterdata/flutter_data#102]
Hi there, any idea why my defined methods haven't been created?

> The method 'getTodos' isn't defined for the type 'Repository'

```
mixin TodoAdapter on RemoteAdapter<TodoModel> {
  Future<Todos> getTodos...
```
I also tried to run build_runner, but the problem persists.

> flutter packages pub run build_runner clean
> flutter pub run build_runner build --delete-conflicting-outputs 
>

**Comment by frank06** [comment]
I apologize in advance for not properly documenting this yet... but these generated methods have been removed (a few months ago already) as they were quite unreliable for non-trivial cases.

I will add in the documentation how to restore them manually.

Curious, what does `getTodos` do? Why not use `findAll`?

**Comment by rubgithub** [comment]
> Curious, what does getTodos do? Why not use findAll?

That was just an example, but I have a lot of `non-trivial` cases. 😥

**Comment by frank06** [comment]
Sorry man, it was a hassle to maintain and I don't want more hassle.

Are you typically using the `deserialize` API when you use `sendRequest`?

If you want to share I can help you optimize the usage of the library. `findAll`, `findOne`, `save` etc are quite flexible and have the advantage of keeping the objects in local storage and offline-ready.

**Comment by frank06** [comment]
@rubgithub in any case, it's pretty straightforward to migrate:

Before:
```
postsRepository.myRequest();
```

After:
```
(postsRepository.remoteAdapter as PostAdapter).myRequest()
// or wherever adapter myRequest is defined in
```

Of course you can still abstract the `myRequest()` call through an `extension`

**Comment by rubgithub** [comment]
> Are you typically using the deserialize API when you use sendRequest?

Yes, I'm.

```
_ret = await sendRequest(hostUri(...
final _model = deserialize(_ret );
```


> If you want to share I can help you optimize the usage of the library. findAll, findOne, save etc are quite flexible and have the advantage of keeping the objects in local storage and offline-ready.

I'm using repositories with DI

```
class TodoRepository implements ITodoRepository {
  TodoRepository (this._repo);
  final Repository<AuthModel> _repo; 
...
   final _ret = await _repo.saveTodo(todo)

```

```
mixin TodoAdapter on RemoteAdapter<TodoModel> {
  Future<Either<Notification, Unit>> saveTodo({
    required TodoModel model,
  }) async {
    try {
      await save(model, remote: false);
```

> Of course you can still abstract the myRequest() call through an extension
I'll check it out.

**Comment by frank06** [comment]
Oh I see. Is this some kind of architecture Resocoder was talking about? I like to keep the boilerplate out.

**Comment by rubgithub** [comment]
> Is this some kind of architecture Resocoder was talking about?

Yep, dartz, freezed, etc.
