### ISSUE TITLE
Repository<xxx> is not registered inside GetIt.

### ISSUE THREAD

**Issue by rubgithub** [flutterdata/flutter_data#103]
Hello,

How flutter_data is dealing with DI?

```
configureRepositoryLocalStorage(
    baseDirFn: () => _dir.path,
    clear: true,
  );
  await getIt.allReady();
```

```
@LazySingleton(as: IAuthRepository, env: [Env.prod]) 
class AuthRepository implements IAuthRepository {
  AuthRepository(this._repo);
```

> E/flutter (18452): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: 'package:get_it/get_it_impl.dart': Failed assertion: line 370 pos 7: 'instanceFactory != null': Object/factory with  type Repository<_AuthModel_> is not registered inside GetIt.

`final _repo = getIt<IAuthRepository>();` //error here

**Comment by frank06** [comment]
Sorry, I am not very familiar with that library. You should wire things manually.
