### ISSUE TITLE
Bug methodForSave (remote_adapter.dart:358)

### ISSUE THREAD

**Issue by corusm** [flutterdata/flutter_data#104]
Hi there :smile:!

Flutter Version: 2.2.2
OS: Windows

# Problem

So I tried to get Flutter_Data to get working. When I was testing my Flutter App I got this output
```
An Observatory debugger and profiler on Windows is available at: http://127.0.0.1:59884/JZVSOQikMCc=/
flutter: null
flutter: [flutter_data] [todos] PATCH http://localhost:3000/%5Ctodos%5C1 [HTTP 404]
 -> body:
 {"id":1,"description":"blah","completed":false}
flutter: [flutter_data] [todos] Error: DataException: {message: Route PATCH:/%5Ctodos%5C1 not found, error: Not Found, statusCode: 404}  [HTTP 404]
```

The Problem here is the `%5C` why the url doesn't reach my server. I am not sure if this problem is windows related.

On this Code:
```
mixin JSONPlaceholderAdapter<Todo extends DataModel<Todo>>
    on RemoteAdapter<Todo> {
  @override
  String get baseUrl => 'http://localhost:3000';

  @override
  String urlForSave(id, Map<String, dynamic> params) {
    return '$type/$id';
  }

  @override
  String get identifierSuffix => 'Id';
}
```

# Possible Solution
remote_adapter.dart:359
 ` Uri.parse('${baseUrl.asUri}/${urlForSave(model.id, params)}') & params,,`

So there is something like this. I haven't tested it yet but I guess it must be changes at every urlforXXX function.
# Thoghts
I am not sure if this Problem is a general one. Maybe its just because Flutter Windows isn't in the stable channel yet.

Thanks for maintaining this repo :+1:

**Comment by frank06** [comment]
Ah, I see.

I have no idea what's going on and it definitely seems to be a Flutter on Windows issue.

What happens if you manually override the `type`, could you let me know if the problem persists?

```
mixin JSONPlaceholderAdapter<Todo extends DataModel<Todo>>
    on RemoteAdapter<Todo> {
  @override
  String get baseUrl => 'http://localhost:3000';

  @override
  String get type => 'todos';

  @override
  String urlForSave(id, Map<String, dynamic> params) {
    return '$type/$id';
  }

  @override
  String get identifierSuffix => 'Id';
}
```

The proposed solution won't have effect as what you wrapped in `Uri.parse` is already an `Uri`.

**Comment by frank06** [comment]
Any updates @corusm ?
