### ISSUE TITLE
Does flutter_data select data source (remote or local) automatically ? 

### ISSUE THREAD

**Issue by thphuc** [flutterdata/flutter_data#107]
I am trying to understand the package. It works, great job.

As the title, I would like to know if the package supports auto-select data source?
Say if we have internet connection, it uses remote adapter, otherwise it uses local adapter?

**Comment by frank06** [comment]
Thank you!  Great question. If you use the watchers (`watchOne`, `watchAll`, etc) data **always** comes from local storage – and gets updated from remotes in the background – so it's the natural choice for offline scenarios. There's a built-in offline adapter that exposes functions for you to retry reaching the remote when the connection is lost.

If you use `findOne` or `findAll`, these go directly to the remote.

Let me know if this clarifies.

**Comment by thphuc** [comment]
Thanks @frank06 it sounds great. Let me do more test and verify this.
