### ISSUE TITLE
Allow ability to provide field to use for deserializing `findAll`

### ISSUE THREAD

**Issue by Zedjones** [flutterdata/flutter_data#108]
The server I'm connecting to returns a paginated response with the following schema:
```
{
  "totalPages": 0,
  "totalElements": 0,
  "pageable": {
    "pageNumber": 0,
    "pageSize": 0,
    "paged": true,
    "unpaged": true,
    "sort": {
      "sorted": true,
      "unsorted": true,
      "empty": true
    },
    "offset": 0
  },
  "sort": {
    "sorted": true,
    "unsorted": true,
    "empty": true
  },
  "first": true,
  "last": true,
  "size": 0,
  "content": [
    {
      "id": 0,
      "username": "string",
      "firstName": "string",
      "lastName": "string"
    }
  ],
  "number": 0,
  "numberOfElements": 0,
  "empty": true
}
```
For `findAll`, there should be a way to tell the deserializer to use the `content` field rather than having to overwrite the entire `deserialize` method. If there's a way to do this easily, I'm not sure. It seems like there _used to be_ a way to override the deserialization of a collection, but I think `deserialize` and `deserializeCollection` were combined at some point.

**Comment by ArneSaknussemm89** [comment]
I actually had a similar problem and he provided a solution for me here: https://github.com/flutterdata/flutter_data/issues/106#issuecomment-892868959

That's the structure I was getting and he provided an example fix.

**Comment by frank06** [comment]
Thank you @ArneSaknussemm89 

Correct, there is no shortcut at the moment.

```dart
mixin SomeAdapter<T extends DataModel<T>> on RemoteAdapter<T> {
  @override
  DeserializedData<T, DataModel> deserialize(dynamic data,
      {bool init, String key}) {
    // whatever condition makes sense for your data
    if (data['content'] is Iterable) {
      return super.deserialize(data['content'], key: key, init: init);
    }
    return super.deserialize(data, key: key, init: init);
  }
}
```
