### ISSUE TITLE
How to handle watchAll/findAll with below special json structure

### ISSUE THREAD

**Issue by thphuc** [flutterdata/flutter_data#110]
Hello again,

Here is our json structure (the structure is from 3rd party, we can not change it):

```
{
    "people": [
         {
             "name": "abc"
         }
    ],
    // Pagination
    "next": "url_to_get_next_results",
    "other_key":  { // other data }
}
```

I understand that we can override **_deserialize_** to parse the "people", but the problem is I can only use findOne (and pass empty id) to get other fileds, is this correct?. 

1. With findOne and empty id, how will the data be saved to local storage?
2. How can we separate the data from "next" page in local storage?
3. Can I use findAll/watchAll in this case?

Thank you!

@frank06

**Comment by frank06** [comment]
@thphuc `deserialize` will handle any incoming data. I do not quite understand why you can only use `findOne`? I also don't think you can pass an empty id. Why can't you use `findAll`?

Have a look at this example: https://github.com/flutterdata/flutter_data/issues/108#issuecomment-903863219

(I am working on the docs at the moment where I hope to explain all this better)

Regarding local storage, if the `deserialize` method successfully completes then your models will be locally stored.

`watchOne` and `watchAll` simply will keep watching local storage for any changes, whether they were generated locally or if the store was updated from a remote call.

Does this help? Let me know

**Comment by frank06** [comment]
Oh I see. I would not design it that way. Models should be models and not contain metadata like `next`. In my experience anytime one starts doing unusual things like that, down the line more issues will appear.

If you use Riverpod you could have a `StateProvider` where to temporarily store the `next` URL and access/update that from `deserialize`.

Also in general, I'm not sure about using `List<Person>`. For relationships make sure you do `HasMany<Person>`.

Use `findAll`, `findOne`, `watchOne`, `watchAll` such that they return models as intended and then leverage the relationship graph to navigate between your models.

**Comment by frank06** [comment]
By the way, you can extend and create your own methods if you think `findAll` and such are not a good fit.

This is just an example coming from a project:

```dart
mixin AppointmentAdapter on RemoteAdapter<Appointment> {
  Future<Appointment> fetchNext() async {
    return await sendRequest(
      baseUrl.asUri / type / 'next',
      onSuccess: (data) {
        return deserialize(data as Map<String, dynamic>, init: true).model;
      },
    );
  }
}
```

So then you'd call something like `(repository.internalAdapter as AppointmentAdapter).fetchNext()`.

**Comment by thphuc** [comment]
Hi @frank06 Thank you again for your suggestion.

I saw HasMany but I completely forgot it when designing my model. 👍 
I will try to follow your suggestion and get back to you.

Things started to be more interesting now with the library 😄

**Comment by frank06** [comment]
Thanks! I'll make sure I add these answers to the docs. Let me know if you have more questions
