### ISSUE TITLE
Question: Riverpod 1.0 support?

### ISSUE THREAD

**Issue by ArneSaknussemm89** [flutterdata/flutter_data#111]
Are there plans for updating to Riverpod 1.0? I took a stab at it, but sadly was not a simple swap over.

**Comment by frank06** [comment]
I was not even aware of Riverpod 1.0... will have a look!

**Comment by frank06** [comment]
Can't find any documentation for 1.0, do you have a link?

**Comment by ArneSaknussemm89** [comment]
He recently updated the docs here: https://riverpod.dev/docs/getting_started

Changelog of the most recent changes:
https://pub.dev/packages/riverpod/versions/1.0.0-dev.7/changelog

Looks closer to being stable, seems the biggest change is no more ScopedProvider or RootProvider and ProviderReference deprecated in favor of ProviderRefBase.

**Comment by ArneSaknussemm89** [comment]
Most recent changelog for Riverpod 1.0.0:
https://pub.dev/packages/riverpod/versions/1.0.0-dev.10/changelog

**Comment by frank06** [comment]
Thanks! Will integrate when it reaches 1.0.0

**Comment by jamesdixon** [comment]
@frank06 looks like it finally hit 1.0 😄
