### ISSUE TITLE
add the ability to deserialize in an isolate

### ISSUE THREAD

**Issue by jamesdixon** [flutterdata/flutter_data#112]
@frank06 hope all is well!

In the Spectora project, there was some code that was written to deserialize templates into Flutter Data models. This works great but we're noticing that some users have large template caches (15MB+) that is causing jank / interface freezing.

Processing these large payloads feels like a tailor-made use case for processing in an isolate, but because of the limitations on what you can do with an isolate, it doesn't seem possible to shoehorn Flutter Data's `deserialize` method into something that be computed in an isolate. That said, I'm wondering if it would be possible to add an option to be able to selectively deserialize a payload in an isolate?

Thoughts?

**Comment by frank06** [comment]
Hey @jamesdixon!  It does make sense but could you provide more detail about the limitations you've encountered when trying to process the deserialization in an isolate?

**Comment by jamesdixon** [comment]
@frank06 sure thing!

So, first off, I was able to greatly increase the performance of this process by about 50x by not transforming the payload into JSON:API and instead deserializing it in its native JSON format. That said, this is still a good candidate for isolates as older devices still don't perform well.

That said, the issue I ran into with deserializing this data in an isolate was mainly because of the fact that the function passed to the isolate has to be top-level or static and I cannot access the adapter's `deserialize` method outside of the adapter.

**Comment by frank06** [comment]
Thank you for your feedback @jamesdixon !

I would think 15+ MB payloads are very uncommon so I won't optimize the adapter for the time being.

I'll leave this open as I'd like to explore the possiblity of taking `deserialize` to isolate land.

**Comment by frank06** [comment]
Tried this with https://pub.dev/packages/async_task without success. It requires a lot of work and it's not a priority, closing.

**Comment by jamesdixon** [comment]
Makes sense!
