### ISSUE TITLE
Breaking changes in 0.8

### ISSUE THREAD

**Issue by danielnordh** [flutterdata/flutter_data#115]
When updating from 0.7.2 to 0.8 (0.8.1 or 0.8.0) builds fail with errors.

When deserializing data in a RemoteAdapter this line:
`final transactions = List<Map<String, dynamic>>.from(data['transfers']);`
gives the following error not present in 0.7.2:
`Error: The operator '[]' isn't defined for the class 'Object'.`

In the same mixin, there is another line:
`return super.deserialize(transactions, key: key, init: init);`
which gives this error, but it might just be because of the first error:
`Error: No named parameter with the name 'init'.`

Full mixin:
<img width="567" alt="image" src="https://user-images.githubusercontent.com/3393669/136543514-944c5141-f0ee-47c9-a5d0-95f257634395.png">

In case it's related, I also get errors with build_runner: 
`flutter packages pub run build_runner build --delete-conflicting-outputs:`
<img width="950" alt="image" src="https://user-images.githubusercontent.com/3393669/136544372-9b827577-55d5-411b-be43-7c8a7f349568.png">

**Edit** - The build errors disappear if overriding analyzer to use 2.0.0 (although I then get new errors from an old auto_route version).

**Comment by frank06** [comment]
I just checked the sample app and the resolved `analyzer` version is `1.7.1`.

Want me to pull from the null-safety migration branch to check out the errors?
