### ISSUE TITLE
Notifier does not update on watchAll after requesting the same repository more than once

### ISSUE THREAD

**Issue by GabrielAraujo** [flutterdata/flutter_data#117]
Hey..

Noticed this when I was adjusting some tests.

When I call the `.watchAll` more than once for the same provider the notifier does not update with the models and the `isLoading` to false..

At the line 80 of `remote_adapter_watch.dart` (`events.singleWhereOrNull`), if the events contains more than one entry with the same `type` and `keys.first` the function will return null making the `doneLoading` attribute being null and therefore the following condition to update the notifier will not be fulfilled.

Obs:
I've managed to make it work by changing the `doneLoading` logic to the following:
```
      final doneLoading = events
          .where((e) =>
              e.type == DataGraphEventType.doneLoading &&
              e.keys.first == internalType)
          .isNotEmpty;
```

@frank06 what do you think about it?

**Comment by frank06** [comment]
@GabrielAraujo thanks! Fixed in 74c654cf9ae5a0bfe895ef218157a84e581e550f

**Comment by GabrielAraujo** [comment]
@frank06 thanks! Any idea on when a new version will be sent to pub.dev?

**Comment by frank06** [comment]
Not sure, point to the git commit for now.  If in the next few days all looks stable I'll release a new version.
