### ISSUE TITLE
Question: Do we save the data locally with findOne?

### ISSUE THREAD

**Issue by thphuc** [flutterdata/flutter_data#118]
I'm trying to use findOne( ), I can see we have a **remote** parameter. But it does not work when I set it to **false**.

Does findOne( ) really save the data to local storage?

**Comment by frank06** [comment]
@thphuc Data is always saved to local storage.  When you set it to `false` you still see a network request? Which version are you on?

**Comment by frank06** [comment]
@thphuc Do you still have this problem or I can close the issue?

**Comment by thphuc** [comment]
Hi @frank06 I am on the latest version (v0.8.2).

Here is the steps:
1. Turn on the wifi and use findOne() to request data from remote
2. Turn off the wifi, use findOne() with remote = false -> There is no data from local.

**Comment by frank06** [comment]
@thphuc I'm not sure what you are doing but it's working for me.

Just came up with a quick sample app. I have this column:

```dart
                  TextButton(
                    child: Text('findOne with remote=true'),
                    onPressed: () async {
                      await ref
                          .read(todosRepositoryProvider)
                          .findOne(1, remote: true);
                      if (localAdapter.findAll().isNotEmpty) {
                        ref.read(_p.notifier).state =
                            'From local storage at ${DateTime.now().millisecondsSinceEpoch}:\n' +
                                localAdapter.findAll().first.description;
                      }
                    },
                  ),
                  TextButton(
                    child: Text('findOne with remote=false'),
                    onPressed: () async {
                      await ref
                          .read(todosRepositoryProvider)
                          .findOne(1, remote: false);
                      if (localAdapter.findAll().isNotEmpty) {
                        ref.read(_p.notifier).state =
                            'From local storage at ${DateTime.now().millisecondsSinceEpoch}:\n' +
                                localAdapter.findAll().first.description;
                      }
                    },
                  ),
                  Text(ref.watch(_p)),
```

Works fine (wait for the whole gif, for some reason it's slow)

![f](https://user-images.githubusercontent.com/66403/143783603-962853f8-b871-4b77-b311-c1c293222f64.gif)


In addition, if instead of retrieving data from local storage I wait for the response (when offline) like this:

```dart
final m2 = await ref.read(todosRepositoryProvider).findOne(1, remote: false);
```

Then `m2` is not null.

I even added a test:

```dart
test('findOne scenario issue #118', () async {
    // cause network issue
    container.read(responseProvider.notifier).state = TestResponse(text: (_) {
      throw HandshakeException('Connection terminated during handshake');
    });

    final family1 = await familyRepository.findOne('1', remote: false);
    expect(family1, isNull);

    container.read(responseProvider.notifier).state = TestResponse.text('''
        { "id": "1", "surname": "Smith" }
      ''');
    await familyRepository.findOne('1', remote: true);

    // cause network issue
    container.read(responseProvider.notifier).state = TestResponse(text: (_) {
      throw HandshakeException('Connection terminated during handshake');
    });

    final family2 = await familyRepository.findOne('1', remote: false);
    expect(family2, isNotNull);
  });
```

I hope you can find what's not working on your end!

**Comment by thphuc** [comment]
Hi @frank06 Thanks again for your kind answer. I guess I need to learn how to use localAdapter

Now, I only use a remote adapter.

By the way, in your example above, how did you create a localAdapter? And how can we "link" this localAdapter with a model?

**Comment by frank06** [comment]
@thphuc You don't need to touch the local adapter API.

The local adapter is used internally by `findOne` – see the test.

In Flutter Data, all models are always coming from local storage. If you happen to make a remote request, the response will be deserialized and stored and then returned to the client.

**Comment by thphuc** [comment]
@frank06 in your app example, under onPressed( ) method of second TextButton, I can see that:

1. You call `.findOne(1, remote: false);` before using localAdapter, is that call required before using local adapter?
2. Because in the demo, you're using localAdapter to check the valid data, I still think I need to touch local adapter API?

Thanks again for your time.

**Comment by frank06** [comment]
No and no. Please use the API like I did on the test snippet.
