### ISSUE TITLE
`LateInitializationError` when calling `repositoryInitializerProvider()`

### ISSUE THREAD

**Issue by jamesdixon** [flutterdata/flutter_data#119]
Hey Frank! Hope all is well man.

Running into an issue as we're migrating to null safety.

During the logout process, we call:

```
await ref.container.refresh(initializerProvider);
```

This triggers the `initializerProvider`, which if you recall, initializes a ton of things. One of those things is this:

```
  await ref.container.refresh(repositoryInitializerProvider());
```

However, when this is triggered, we get the following error:

```
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: LateInitializationError: Field 'adapters' has already been initialized.
#0      LateError._throwFieldAlreadyInitialized (dart:_internal-patch/internal_patch.dart:211:5)
#1      _RemoteAdapter.adapters=
package:flutter_data/…/repository/remote_adapter.dart:50
#2      _RemoteAdapter.initialize
package:flutter_data/…/repository/remote_adapter.dart:166
#3      Repository.initialize
package:flutter_data/…/repository/repository.dart:31
#4      _repositoryInitializerProviderFamily.<anonymous closure>
package:spectora_mobile/main.data.dart:93
<asynchronous suspension>
#5      initializerProvider.<anonymous closure>
package:spectora_mobile/main.dart:67
<asynchronous suspension>
#6      SessionService.logOut
package:spectora_mobile/services/session_service.dart:242
<asynchronous suspension>
#7      MenuDrawer.build.<anonymous closure>
package:spectora_mobile/widgets/menu_drawer.dart:187
<asynchronous suspension>
```

Any workaround for this?

Thanks man!

**Comment by frank06** [comment]
Hey James!

It's fixed already in https://github.com/flutterdata/flutter_data/commit/15e93536de4ae467e0fc23c28925100284ce14a4#diff-4268e47c73207c27811d615913d30f00c650e7473285bf9099011dd7b27a71d0

I want to finish a few other things before releasing a new version.

**Comment by jamesdixon** [comment]
@frank06 thanks! Will we need to upgrade our app to Riverpod 1.0 to use this?

**Comment by frank06** [comment]
Yes. Or you could patch the code and make `adapters` and other mutable instead of `late final`s

**Comment by jamesdixon** [comment]
Got it! Thx man!

**Comment by jamesdixon** [comment]
@frank06 ping me when you've released a new version so we can make this upgrade. Appreciate it!
