### ISSUE TITLE
expose underlying adapter serializer / deserializer

### ISSUE THREAD

**Issue by jamesdixon** [flutterdata/flutter_data#12]
Use case:

**Serializing:** if I need to write a custom adapter method, I'd like to be able to serialize the payload automatically into JSON API rather than manually building it. I did try the `serialize` method on the repository, but it just spit out plain json.

**Deserializing:** again, if I build a custom adapter method that has a payload that needs to make its way into the store, I need a way to do this. Maybe that's part deserialization, part something else.

**Comment by frank06** [comment]
In order to serialize JSON:API you can do the following in your own adapter:

```dart
serialize(jsonApi);
```

as long as the `JSONAPIAdapter` mixin precedes your adapter in your model's mixin declaration:

```dart
@DataRepository([JSONAPIAdapter, YourCustomAdapter])
class User extends DataSupport<User> { ... } 
```

The same goes for `deserialize`.
