### ISSUE TITLE
How to pass id with findOne when offline?

### ISSUE THREAD

**Issue by nhatvu95** [flutterdata/flutter_data#122]
I have a question with findOne url which does not contain “id”, I already can custom the url to get remote data. However, when offline, if I want to call findOne again, I will need to provide an id (to find that object in local storage). Is that correct?
(I tried to put a fixed id when offline but can not retrieve the data from local storage)

**Comment by frank06** [comment]
Correct. You can hit a remote endpoint such as `/me` and that payload should return an ID. You should use that ID to retrieve it from local storage. All local storage resources are only addressable by a type and an ID.

**Comment by nhatvu95** [comment]
I tried to add ID when loading local data, but No data returned from local.
![Screen Shot 2021-12-14 at 10 28 30](https://user-images.githubusercontent.com/40544173/145928029-6a643b51-c383-4ce0-af86-dbbe2aec5804.png)

**Comment by frank06** [comment]
I can't do much with the information you provide. What operations did you do before this? What was the payload?

A useful thing you could share with me is `graph.toMap()` in those lines you're debugging.

**Comment by nhatvu95** [comment]
Hi @frank06 ,

In my graph.toMap(), I can see the object key and id there (screenshot below), does that mean the object (from findOne) is saved to local storage successfully?

![Screen Shot 2021-12-14 at 22 45 59](https://user-images.githubusercontent.com/40544173/146031236-b1fd9be7-272a-4d15-9ac1-a3268b9c7f46.png)

---
However, when we use localAdapter.findOne to get the model, it returns null.
![Screen Shot 2021-12-14 at 22 49 49](https://user-images.githubusercontent.com/40544173/146032152-cfe28a83-f973-4ed1-812e-4cfb08e18572.png)

I also tried to save the model (when remote = true) manually but no luck.
`_myProfileRepo.save(myProfiles, remote: false);`

**Comment by frank06** [comment]
This is strange because we have a test covering this exact case.

Could you please send me the exact method you're invoking prior to this (`findOne` with `remote=true`, is it overridden? How?) and the exact server response payload?

Also when debugging, what is the output of:

```dart
(localAdapter as HiveLocalAdapter<ProfileMes>).box!.keys
```

**Comment by nhatvu95** [comment]
Hi @frank06 

Model :
![Screen Shot 2021-12-15 at 08 33 07](https://user-images.githubusercontent.com/40544173/146106460-64c3fa86-02b3-492f-a91b-e43f884ec3b6.png)

Adapter :
![Screen Shot 2021-12-15 at 08 33 40](https://user-images.githubusercontent.com/40544173/146106507-da0ae6c2-2c44-431e-bb96-f462df4a16ff.png)

findOne : 
![Screen Shot 2021-12-15 at 08 34 11](https://user-images.githubusercontent.com/40544173/146106555-9cc9703e-6b9f-4910-a0a6-8649b392b871.png)

**Comment by nhatvu95** [comment]
Hi @frank06  ,
 Please help me when you have free time. I'm still waiting for you, thanks!

**Comment by frank06** [comment]
@nhatvu95 I need you to understand that if you don't send me the exact response from your API I cannot help you.

Also, what is `ProfileMes`? Is that a type? Show me the definition for that model. What does it stand for? It's confusing to follow.

If your model is `PersonDetail` then I would like to see `(localAdapter as HiveLocalAdapter<PersonDetail>).box!.keys` and please the full response payload from your API.

**Comment by nhatvu95** [comment]
@frank06  my model is PersonDetail

Api response:
![Screen Shot 2021-12-16 at 00 58 12](https://user-images.githubusercontent.com/40544173/146240575-965abdf6-ec53-4d58-ad72-45a92ac8ace6.png)

`(localAdapter as HiveLocalAdapter<PersonDetail>).box!.keys`
![Screen Shot 2021-12-16 at 01 01 21](https://user-images.githubusercontent.com/40544173/146240674-9e4c0505-5f89-48b6-965d-20cc32cff2a3.png)

**Comment by frank06** [comment]
Interesting. I'm not sure what it is, as we have tests that should reproduce this:

https://github.com/flutterdata/flutter_data/blob/master/test/repository/repository_test.dart#L81-L112

My suggestions would be: if you are debugging try stepping into `super.deserialize` and see what happens in these lines:

https://github.com/flutterdata/flutter_data/blob/master/lib/src/repository/remote_adapter_serialization.dart#L89-L93 , more specifically line 91.

Or otherwise could you share your code and/or API with me so I can debug it myself?

**Comment by frank06** [comment]
Were you able to solve the issue?

**Comment by nhatvu95** [comment]
Hi @frank06 ,
Sorry for the delay, I have solved my issue.

**Comment by frank06** [comment]
@nhatvu95 would you mind sharing how you fixed it?
