### ISSUE TITLE
package analyzer is too old, please update.

### ISSUE THREAD

**Issue by huang12zheng** [flutterdata/flutter_data#126]
* [newest version](https://pub.flutter-io.cn/packages/analyzer) is 3.0.0
* but version in this package is just 2.0.0

* question:
Is it acceptable to generate an ActionBot to automatically generate PR?

**Comment by huang12zheng** [comment]
Why restrict  json_annotation?

**Comment by frank06** [comment]
Have you tried upgrading these dependencies and running tests? Do they all pass?

What are good reasons to place the builder in another package?

**Comment by huang12zheng** [comment]
> Have you tried upgrading these dependencies and running tests? Do they all pass?
* one hand
There was a problem before, so I split it up. 
But more specific details cannot be provided because of oblivion.
* another hand,But it is currently upgradable

> What are good reasons to place the builder in another package?
1. flutter_data  is no dependency required For some packages, which is dependency of flutter_data_generator.
2. furthermore, The size of release may be beneficial
