### ISSUE TITLE
ability to push payload into local store

### ISSUE THREAD

**Issue by jamesdixon** [flutterdata/flutter_data#13]
What's the best way to take a raw JSON API (or whatever) payload and get into the local store?

Thinking something along the lines of Ember's `store.pushPayload()` method.

Maybe somewhat related to #12

**Comment by jamesdixon** [comment]
Just tried the following and I believe this works:

```dart
    final customer = json.decode(response.body) as Map<String, dynamic>;
    await repository.save(Customer.fromJson(customerAttrs), remote: false);
```

If that's correct, thoughts on maybe offering some syntactic sugar on top?

```dart
await repository.pushPayload(customerAttrs);
```

**Comment by frank06** [comment]
With the new serialization formats branch, it will be possible to do:

```
// in adapter mixin

final customer = json.decode(response.body) as Map<String, dynamic>;
deserialize(customer);
```

**Comment by frank06** [comment]
Notice there's no need to "save", deserialization initializes models which stores them locally.

See #12
