### ISSUE TITLE
Question: How to combine and save data from 2 separate (but related) APIs 

### ISSUE THREAD

**Issue by thphuc** [flutterdata/flutter_data#132]
Hello @frank06 

I have 2 APIs:
1. The API to get a list of tags: **/tags**. This API returns a list of tags (each tag has an id and a name). We can use the tag id to call the below API (pass the id) to get a list of people.
2. The API to get list of people: **/tags/${tagId}/people**. This API returns a list of people under the tag. 

I already can save the tags list for offline.
1. Is it possible to save the people list for offline mode in this case? 
OR
2. Is it possible to add/extend the people list to an existing tag to use it later when offline?

Thanks!

**Comment by thphuc** [comment]
Hi @frank06 

I already follow exactly that approach to override urlForFindAll and can get the data.
However, I don't know how to design the data model to make the offline work for people (the tag is working well, but people).
Can you share an example of how to design the models? (Tag and People)

**Comment by ryanfieldedge** [comment]
To hopefully add some further clarity to what @thphuc said:

We can save the array of tags returned by the first API call, eg. tag_1, tag_2, tag_3 – no problems there.

But what we are having trouble with is: saving the array of people returned from the second API call  – the one to fetch the people associated with a specific tag.

A user should be able to tap a tag and then view the associated people, while offline.

**Comment by frank06** [comment]
If by saving you mean saving locally that is done upon deserialization. If the API call is successful your models are already in local storage. I wish we had an easy way to explore the local data.

Using relationships does not work? 

```dart
final tag = await findOne('tag_1', remote false);
final people = tag.people;
```

But I don't know how you have these wired up. Could you share your models and the code you are using to fetch?

**Comment by thphuc** [comment]
Hi @frank06 Thanks for your prompt reply

Here are my models

```
@JsonSerializable()
@DataRepository([BaseAdapter, TagAdapter])
class Tag extends DataModel<Tag> {
  final String? id;
  @JsonKey(name: 'name')
  final String? tagName;
  @JsonKey(name: 'taggings_count')
  final int? taggingsCount;

  Tag({this.id, this.taggingsCount, this.tagName});

  factory Tag.fromJson(Map<String, dynamic> json) {
    Tag tag = Tag(
        id: json['name'],
        taggingsCount: json['taggings_count'],
        tagName: json['name']);
    return tag;
  }

  Map<String, dynamic> toJson() => _$TagToJson(this);
}
```

```
mixin TagAdapter on RemoteAdapter<Tag> {
  String? next;

  @override
  String urlForFindAll(Map<String, dynamic> params) {
    return 'tags';
  }

  @override
  DeserializedData<Tag, DataModel> deserialize(Object? data,
      {String? key}) {
    if (Map.from(data as Map)['results'] != null) {
      final List results = Map.from(data)['results'];
      next = Map.from(data)['next'];
      // ignore: unnecessary_type_check
      if (results is Iterable) {
        return super.deserialize(results, key: key);
      }
    }

    return super.deserialize(data, key: key);
  }
}
```

```
@JsonSerializable()
@DataRepository([BaseAdapter, TagPeopleAdapter])
class TagPeople extends DataModel<TagPeople> {
  @override
  final int? id;
  final List<dynamic>? people;
  final String? next;

  TagPeopleDetails({this.results, this.next, this.id});
}
```

```
mixin TagPeopleAdapter on RemoteAdapter<TagPeople> {
  @override
  String urlForFindOne(id, Map<String, dynamic> params) {
    return 'tags/$id/people';
  }
}
```

To fetch the people under a tag (work well when online):
```
_tagPeopleRepo.findOne(tagId, // other params...);
```

So far, I haven't figured out how to link tagPeople.people to a tag (to save it locally for offline usage later).
Do you have any suggestions?

Thanks a lot!

**Comment by frank06** [comment]
Yes, please learn about relationships and use them: https://flutterdata.dev/docs/relationships/

**Comment by thphuc** [comment]
Hi @frank06 

From the above document:

> So long as:
> 1. Models have all their relationships initialized
> 2. The API responds correctly with relationship data (for example a User resource with a collection of Task models – or just IDs if models are already present in local storage)

- For 1: I already added HasMany<TagPeople> to Tag and BelongsTo<Tag> to TagPeople -> Is this a right setup for point 1?

- For 2: our API does not return any collection of people or people IDs at all. We can only get list of people by calling another separate API using tag id. Do you have any idea for this situation?

cc @ryanfieldedge

**Comment by frank06** [comment]
It looks like a many-to-many relationship, so a `HasMany` on both sides? 

`TagPeople` appears to be a proxy model. Why? Models should be modelling real-world data. Use a proper `Person` model and leave the plumbing to adapters.

If you retrieve a bunch of `Person` who don't have their `Tag`s, you could override `deserialize` for `Person` and append it to the JSON (I suppose: `tags: ['x']`) before calling `super.deserialize`.

**Comment by thphuc** [comment]
Hi @frank06 

I found a working approach (I'm not sure if it's the best though).
In Tag class, I added HasMany:

```
@JsonKey(ignore: true)
 final HasMany<TagPeople>? people;
```

Then after getting people (of a tag), I add this list of people to the tag and save it manually. When offline, I check the network status, if offline, I just return tag.people.toList().
