### ISSUE TITLE
reinitialization error

### ISSUE THREAD

**Issue by jamesdixon** [flutterdata/flutter_data#133]
@frank06!

Question for ya: in the Spectora app, there is the following line of code in the `initializerProvider` that is called when the app starts:

```dart
  // Initialize Flutter Data repositories
  // (use refresh to enable re-initialization)
  // DO NOT use `repositoryInitializerProvider().future`
  // when refreshing as it will not actually refresh
  ref.refresh(repositoryInitializerProvider());
```

This lines up with what you mention in the Flutter Data documentation, but when I do a hot reload, I see the following exception:

![image](https://user-images.githubusercontent.com/110114/150863120-062e372e-9552-465a-ba74-bcd3a21896b4.png)

`_adapters` is `null`.

However, if I do

```dart
await  ref.refresh(repositoryInitializerProvider().future);
```
it appears to work as expected even though your comment indicates that it doesn't actually work.

Thoughts? Has something changed since that comment was written?

We're running Flutter Data 1.1.1.

**Comment by frank06** [comment]
Hey @jamesdixon ! To be honest I have no idea. Most likely Riverpod changed quite a bit.

I need to check but use whatever works!
