### ISSUE TITLE
Setting baseUrl from sharedPreferences or from other not hardcoded place

### ISSUE THREAD

**Issue by DRN88** [flutterdata/flutter_data#135]
Hello!

First of all, I like flutterdata very much. Thank you for it!

I was wondering if I can set basic api required configs for my models/repos in sharedPreferences or from somewhere else? ( basic auth username, password and api baseUrl for starters )
I would like to give the app user this functionality from a Settings page.

Thank you for your reply in advance.

**Comment by frank06** [comment]
@DRN88 absolutely. For example in one of my apps we're doing

```dart
  @override
  String get baseUrl => ref.read(configurationProvider).instance.apiUrl;
```
