### ISSUE TITLE
Question: How to model Many-to-One with ID from API

### ISSUE THREAD

**Issue by stephane-segning** [flutterdata/flutter_data#140]
Suppose I have these responses from an API:
- A Chat
  ```json
  {
      "id": "some-chat-id",
      "name": "Some chat name"
  }
  ```

- And a chat item (a message)
  ```json
  {
      "id": "some-chat-item-id",
      "name": "Some chat item name",
      "chatId": "some-chat-id"
  }
  ```

I want to model it using a `HasMany` and `BelongsTo` but I don't have any idea how to do it. How should I map chat `chatId` to `Chat` using the framework ?

**Comment by frank06** [comment]
By default the JSON serializer will look up relationships with the field name + `_id`, so in your case `chat_id`. You can change it to `chatId` by overriding `identifierSuffix` on your adapter. Let me know if this worked for you!

**Comment by stephane-segning** [comment]
Hello, Thanks for the quick answer. I'm going to test it today. I'll close if all's perfect 👌🏿
