### ISSUE TITLE
Question: How to automatically load `BelongsTo` relation?

### ISSUE THREAD

**Issue by stephane-segning** [flutterdata/flutter_data#142]
Right now I'm having an issue I didn't noticed before, cause my objects where already stored locally. I've fetched data from the remote and I do have such models:
- A Chat
  ```json
  {
      "id": "some-chat-id",
      "name": "Some chat name"
  }
  ```

- And a chat item (a message)
  ```json
  {
      "id": "some-chat-item-id",
      "name": "Some chat item name",
      "chat_id": "some-chat-id"
  }
  ```

Using dart, the code seems like following:
- First the 
  ```dart
  @freezed
  @DataRepository([CoreAdapter, HttpProxyAdapter, ...])
  class Chat extends DataModel<Chat> with _$Chat {
    Chat._();
  
    @JsonSerializable(explicitToJson: true)
    factory Chat({
      String? id,
      String? name,
    }) = _Chat;

    ...
  }
  ```

- And now the reference:
  ```dart
  @freezed
  @DataRepository([CoreAdapter, HttpProxyAdapter, ...])
  class ChatItem extends DataModel<ChatItem> with _$ChatItem {
    ChatItem._();
  
    @JsonSerializable(explicitToJson: true)
    factory ChatItem({
      String? id,
      String? name,
      required BelongsTo<Chat>? chat
    }) = _ChatItem;

    ...
  }
  ```

When I get a `Chat` before getting the `ChatItem`, all's right. But some special cases, I first get the `ChatItem` and I want to have the `Chat`. But the problem is, that the property `chat` is a BelongsTo object which value is `null`. But there are keys in that object. 

Now may I know a way to automatically get these objects?

**Comment by frank06** [comment]
To prevent getting a null you should set an empty BelongsTo beforehand or make it non-nullable.

Have a look at Defaults here: https://flutterdata.dev/docs/relationships/

**Comment by stephane-segning** [comment]
I've read the page. Maybe my question wasn't clear enough. Actually the `BelongsTo` is a non-nullable field and I get the `id` correctly. But, not the **whole object**. Only the _id_. When doing `chatItem.chat.id`, I get the correct id. But `chatItem.value` is `null`.

**Comment by frank06** [comment]
Oh I see. No, there is no way to automatically load objects, you need to do it explicitly.

```dart
await chat.find();
```

**Comment by stephane-segning** [comment]
Ok, I get it. Just for the info, the method `find` does not exist on `BelongsTo`, reason why I've been using the mechanism described here https://github.com/flutterdata/flutter_data/issues/143#issuecomment-1051391243.

Plus there's also a `watch` method which returns a `DelayedStateNotifier<E?>` aka `StateNotifier<T>`.

**Comment by frank06** [comment]
Then I meant `await chatItem.chat.value.find();` and make sure you import FD on that file

**Comment by stephane-segning** [comment]
Thanks for the comprehension. Now using the `repository.findOne(chatItem.chat.id)` mechanism, I get the error described in the second issue (#143).
