### ISSUE TITLE
Override the methods used by Adapters (findOne, findAll, etc.)

### ISSUE THREAD

**Issue by alguintu** [flutterdata/flutter_data#147]
Is there a way to override the methods in adapters to completely control how the data is fetched? I'm using a postgREST api backend with a postgrest client, and I can't figure out a way to make it compatible with the current adapters, short of handling these methods myself. Would this be possible?

**Comment by frank06** [comment]
I'm not familiar with postgrest, but all methods are overridable including `sendRequest`. Have you tried it?

**Comment by alguintu** [comment]
I have dived into the source code more in the past days and figured it out. It's all working nicely now. Thank you!
