### ISSUE TITLE
HasMany does not work when offline

### ISSUE THREAD

**Issue by thphuc** [flutterdata/flutter_data#148]
Hi @frank06 

I have some models designed like below:

```
@JsonSerializable(anyMap: true)
@DataRepository([BaseAdapter, SiteDetailAdapter])
class SiteDetail extends DataModel<SiteDetail> {
  @override
  final int? id;
  String? name;
  final HasMany<Question>? questions;

  SiteDetail(this.id,
      {this.name,
      this.questions,});

  factory SiteDetail.fromJson(Map<String, dynamic> json)  => _$SiteDetailFromJson(json);
```

```
@JsonSerializable(anyMap: true)
@DataRepository([RemoteAdapter])
class Question extends DataModel<Question> {
  @override
  final int? id;
  String? prompt;
  String? type;
  String? status;

  Question(this.id, {this.prompt, this.type, this.status});
  factory Question.fromJson(Map<String, dynamic> json) => _$QuestionFromJson(json);
  Map<String, dynamic> toJson() => _$QuestionToJson(this);
}
```

It works well when online but when offline, all the questions are empty.

I printed the SiteDetail list:

```
// OFFLINE
[
    "SiteDetail{id: 1012, name: Cat or Dog Pages, slug: cat_pages, domain: null, status: published, isSelected: null, questions: HasMany<Question>()}",
    "SiteDetail{id: 11, name: Survey test, slug: survey_test, domain: null, status: published, isSelected: null, questions: HasMany<Question>()}"
]
```

```
// ONLINE
[
    "SiteDetail{id: 1012, name: Cat or Dog Pages, slug: cat_pages, domain: null, status: published, isSelected: null, questions: HasMany<Question>(1022, 1025)}",
    "SiteDetail{id: 11, name: Survey test, slug: survey_test, domain: null, status: published, isSelected: null, questions: HasMany<Question>(21, 19, 20)}"
]
```

Is Anything wrong with the models I designed?

**Comment by frank06** [comment]
Have you upgraded to FD 1.2.1?

If not, since your model has multiple words, it's likely it has to do with this bug: https://github.com/flutterdata/flutter_data/commit/dba64d8e6051f40e19c08fc5ac921da683ccfeef

**Comment by thphuc** [comment]
Hi @frank06 

I'm still using the old version (0.8.2). I will try the latest version. Thanks.

1. By the way, if multiple words is the problem, can I rename my model to a single word to fix it?

2. Can I just use List<Question> under my SiteDetail? (Instead of HasMany<Question>, because the question list are under SiteDetail response - sometimes it misses questions)

**Comment by frank06** [comment]
For relationships to work you must use `HasMany`. On 1.2.1, did you clear the cache and re-ran codegen? Also, try passing `clear: true` (or uninstall the app from the simulator). Do you get the same result?

**Comment by thphuc** [comment]
Let me try:
- clear cache + re-run codegen
- passing clear: true 

I will update you later today. Thanks again @frank06

**Comment by frank06** [comment]
Flutter Data is working in similar scenarios on other applications. I am not sure what it's happening, were you able to debug the issue and provide further information?

Probably unrelated: What are you trying to accomplish by using `@DataRepository([RemoteAdapter])`? Looks very unusual.
 Why is one model using a `BaseAdapter` and the other one not?

**Comment by oarshad** [comment]
I am having the same issue where `findAll(remote: false)` doesn't bring the `HasMany` data. It worked while using `watchAllNotifier(remote: false)`. However, I see in the new versions of flutter_data `watchAllNotifier` isn't present anymore. Is there a reason to remove `watchAllNotifier` ?

**Comment by frank06** [comment]
@oarshad you can still access the notifier by `ref.read(modelsProvider().notifier)`.

What do you mean by `findAll` not bringing `HasMany` data? The models returned by `findAll` have broken relationships? Please clarify and provide some examples so I can look into it.

**Comment by oarshad** [comment]
@frank06 I have created a simple demo application to explain the problem:

https://github.com/oarshad/flutter_data_demo

There are two buttons, `Remote Data` and `Offline Data`.

Replicate Steps:
When you run this application for the first time and hit `Offline Data`. It doesn't print anything on the console, as there is no data. After that, if you hit `Remote Data`, it does fetch the data from remote and prints all entries along with its child relationships.

Once `Remote Data` is already pressed, you can hit `Offline Data` many times and it works as expected whereas printing complete entities along with their relationships.

However, if you now re-install the application and then start with `Offline Data`, it prints only the main entities and doesn't print child relations. I guess child entities never got initialized until called `Remote Data` again.

**Comment by frank06** [comment]
I appreciate that @oarshad ! I will soon have a look

**Comment by oarshad** [comment]
that seems to be working fine 👍 

Thank You @frank06
