### ISSUE TITLE
URL-Resolution is broken on Windows

### ISSUE THREAD

**Issue by Skycoder42** [flutterdata/flutter_data#149]
I am currently playing around with the library and found a bug. Urls are not constructed correctly on windows. On other platforms, a URL might look like this:
```
https://example.com/app/testModels
```
However, on windows, we get this:
```
https://example.com/%5Capp%5CtestModels
```

As you might have already guessed, `%5C` is the `\` character. I took a look at your code and found the problem. In `UriUtilsX.operator/` (https://github.com/flutterdata/flutter_data/blob/master/lib/src/utils/extensions.dart#L75), you use `path_helper.normalize`, which, as far as I can see, is the [normalize](https://pub.dev/documentation/path/latest/path/normalize.html) method of the path package.

The problem here is, that path will try to automatically detect the platform you are running on and use different path stlyes depending on that:

> We've tried very hard to make this library do the "right" thing on whatever platform you run it on, including in the browser. When you use the top-level functions, it will assume the current platform's path style and work with that. If you want to explicitly work with paths of a specific style, you can construct a [p.Context](https://pub.dev/documentation/path/latest/path/Context-class.html) for that style.

The solution here is easy: Simply use the `posix` context, e.g.:
```dart
  Uri operator /(String path) {
    return replace(path: path_helper.posix.normalize('/${this.path}/$path'));
  }
```

**Comment by frank06** [comment]
Thanks @Skycoder42 . I cannot test on Windows but tests pass on Mac/Linux.
