### ISSUE TITLE
support for interceptors

### ISSUE THREAD

**Issue by jamesdixon** [flutterdata/flutter_data#15]
Just adding this here as a reminder :) 

FYI there is an [http_inteceptor](https://pub.dev/packages/http_interceptor) package built to work with `http`. Dio also has them built-in.

**Comment by frank06** [comment]
Thanks for the library! Yes, I will expose an interceptor API soon.

**Comment by frank06** [comment]
It's just a matter of overriding `withResponse` in your adapter:

```dart
  @override
  FutureOr<R> withResponse<R>(
      http.Response response, OnResponseSuccess<R> onSuccess) {
    if (response.statusCode == 401) {
      // do sth
    }
    return super.withResponse(response, onSuccess);
  }
```
