### ISSUE TITLE
Question: Migrate from Existing Hive Model with custom type id and want to open with custom box name

### ISSUE THREAD

**Issue by user97116** [flutterdata/flutter_data#154]
Suppose this is 1'st todo model which is in flutter_data and 2nd is in hive model, 2'nd hive model is existing model, I want migrate with same typeid and hive field id so I don't loss data when I open model and also I didn't find anyway to open with custom box name with flutter_data

1'st
```
import 'package:flutter_data/flutter_data.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'todo.g.dart';
@JsonSerializable()
@DataRepository([])
class Todo with DataModel<Todo> {
  @override
  final String id;

  String name;
  bool complete;
  Todo({
    required this.id,
    required this.name,
    required this.complete,
  });
}
```

2nd
```
import 'package:flutter_data/flutter_data.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'todo.g.dart';
@HiveType(typeId:3)
class Todo with HiveObject {
 @HiveField(0)
  String name;
 @HiveField(1)
  bool complete;
  Todo({
    required this.name,
    required this.complete,
  });
}
```

**Comment by frank06** [comment]
It is not possible to customize box names or type IDs or even the data format, all of this is managed internally by Flutter Data which uses its own boxes.

You should create a custom migration in your app where you load old boxes, copy data over to FD and then destroy the old boxes.
