### ISSUE TITLE
some confusion about test usecase init

### ISSUE THREAD

**Issue by huang12zheng** [flutterdata/flutter_data#156]
https://github.com/flutterdata/flutter_data/blob/master/test/model/data_model_test.dart#L14-L31
* confusion 1
I found comment here in the source `test/model/data_model_test.dart`
```dart
  test('init', () async {
    final familia = Familia(id: '55', surname: 'Kelley');
    // since it is init but NOT saved, we can't find it   //<<<
    expect(await container.people.findOne('55', remote: false), isNull);  //<<<
```
But, this use case doesn't need person.save(), or person.init()
In particular, I looked at the  DataModel, and RemoteAdapter. 
DataModel would do init.

```dart
DataModel() {
    final _isRepoInitialized = internalRepositories.containsKey(_internalType);
    if (_isRepoInitialized && remoteAdapter.autoInitializeModels) init();
  }
abstract class _RemoteAdapter... {
...
bool get autoInitializeModels => true;
```
---

* confusion 2
You new Familia, but api is to people.findOne. why not familia.findOne?
----

here is my test code  with '//<<<' as change
```dart
  test('init', () async {
    final familia = Familia(id: '55', surname: 'Kelley');
    // since it is init but NOT saved, we can't find it
    expect(await container.people.findOne('55', remote: false), isNull);
    expect(await container.familia.findOne('55', remote: false), isNotNull); //<<<

    final person = Person(id: '1', name: 'John', age: 27, familia: familia.asBelongsTo);
    // await person.save();  //<<<

    // redundantly init'ing has no effect
    // person.init();   //<<<

    // (1) it wires up the relationship
    expect(person.familia.key, graph.getKeyForId('familia', '55'));

    // (2) it saves the model locally
    expect(person, await container.people.findOne(person.id!, remote: false));
  });
```

**Comment by frank06** [comment]
It was a bug in the test, fixed

**Comment by huang12zheng** [comment]
Sorry, I didn't see your reply.

By the way,  I want to ask you a question,
`await person.save();`
It is no need.  Function save would do in init(save = true) by default , and init do in construction of DataModel.
> Is there anything else you'd like to test? But I don't get it?

**Comment by frank06** [comment]
In this particular case that is technically true, but `save` is not at all the same as `init`.  Saving during `init` only silently saves to local storage.
