### ISSUE TITLE
RelationshipMeta.instance maybe a little confusion

### ISSUE THREAD

**Issue by huang12zheng** [flutterdata/flutter_data#157]
When I see the generated _kUserRelationshipMetas, I'm a little confused, 
why is this instance
> I did, and also today, treat Instance as a DataModel. -_-||
I later found out that its signature is as follows:
```dart
RelationshipMeta
final Relationship? Function(DataModel) instance;
```

It might be better to use some words for function concept.
such as, create , resolverRelationship

**Comment by frank06** [comment]
Those are Flutter Data internals. What are you trying to do?
