### ISSUE TITLE
access relationship directly instead of using `relationship.value`

### ISSUE THREAD

**Issue by jamesdixon** [flutterdata/flutter_data#16]
Super minor thing, but just calling out things that weren't immediately obvious.

I went to access a relationship `staff.account` and didn't realize I needed to actually access `staff.account.value` to get the properties of that relationship.

Again, not a big deal at all. Just documenting things :)

Feel free to close 👍

**Comment by frank06** [comment]
Thanks, this will definitely be available in the documentation I'm working on.
