### ISSUE TITLE
v1.4.0: DataModel can't be used as a mixin because it declares a constructor

### ISSUE THREAD

**Issue by alguintu** [flutterdata/flutter_data#165]
Upgraded to 1.4.0 and I'm getting this message on all models trying to use the DataModel mixin.

``` class Item with DataModel<Item> ```

What's the proper way to use the DataModel now? Should I just extend it since it now has a constructor?

``` class Item extends DataModel<Item> ```

**Comment by huang12zheng** [comment]
You can check file `example/lib/models/task.dart`
it show now use extends instead of with
@alguintu

**Comment by frank06** [comment]
@alguintu Yes you need to use `extends` (no more need for `init(...)`).

I am thinking of adding a `DataModelMixin<T>` to 1.4.1 for those who still want to keep calling `init()`/don't want to use extends.

I will be starting to update the documentation today.
