### ISSUE TITLE
Question: how to get local state?

### ISSUE THREAD

**Issue by huang12zheng** [flutterdata/flutter_data#169]
I want get localState.
But I only know how to get data by model.
> In other word, `container.people.watch(T())`

But I realized that my local value would be replaced.

> It should be because https://github.com/flutterdata/flutter_data/issues/156 mentioned in the init to save
```dart
test('check ID Value', () async {
    final p = Person(id: '0', name: 'Luis');
    final pTest = Person(id: '0', name: 'ab');
    // await container.people.save(p);
    print(keyFor(pTest));
    final p2 =
        container.people.remoteAdapter.localAdapter.findOne(keyFor(pTest))!;
    print(p);
    print(pTest);
    print(p2);
    expect(p, p2);
    expect(keyFor(p), keyFor(p2));
  });
```

I just want to get (0,Luis) which is want I save in local.

**Comment by frank06** [comment]
Initialization is saving by default, so it's to expect that you get `(0, 'ab')`.

If you want to disable saving on init, do this: https://github.com/flutterdata/flutter_data/blob/master/test/_support/node.dart#L21

**Comment by frank06** [comment]
For local data you can also do `await container.people.findOne('0', remote: false)`

**Comment by frank06** [comment]
I just changed this. Now all models are initialized but you need to manually save them, so your original example should work.

https://github.com/flutterdata/flutter_data/blob/master/test/_support/node.dart#L21 now does the opposite (it's auto-saving – but note this will likely break the ordering https://github.com/flutterdata/flutter_data/issues/167)

**Comment by huang12zheng** [comment]
> For local data you can also do `await container.people.findOne('0', remote: false)`

It turns out to be future with key `await`, 
The Future could be difficult to use in Widget.build and is probably better as follow
```dart
container.people.watchOne('0', remote: false).model!
```
By the way, If the program is running properly, there is a block of app data in memory, we don't need a future.
