### ISSUE TITLE
flutter data needs to be imported to access extensions

### ISSUE THREAD

**Issue by jamesdixon** [flutterdata/flutter_data#17]
This one got me as I didn't realize some methods that were available on a model, such as `save()` were defined as extensions.

That said, is it necessary to have these defined as extensions? Could they not be class methods?

If it is necessary, definitely something to mention in the docs.

**Comment by frank06** [comment]
Right, `save()` on the model is syntax sugar defined in an extension. It is equivalent to:

```dart
repository.save(model);
```

so you can use that.

Due to compatibility with freezed we can't have public methods in the `DataSupport` class.
