### ISSUE TITLE
Question: Non-trivial examples for more complex use-cases?

### ISSUE THREAD

**Issue by alguintu** [flutterdata/flutter_data#171]
Is there an existing example project that uses this library extensively, in real-world scenarios beyond simple tasks list? I'm having troubles using the repositories in multiple widgets across a single activity, e.g. two ListViews where each list watches a different subset of a repository. And also some samples on how to consume the results of a findAll in a HookWidget.

I've been try to search for a couple days now but examples are too few and far between.

**Comment by frank06** [comment]
For what it's worth, Flutter Data is the cornerstone of a decent-sized app (flagship product and main source of revenue of an established startup), so yes a very real world scenario. And there are several more. Sorry I didn't have the time to write a bigger example yet, I'm trying to find the time.

Please open an issue with what you have tried (with some code please) and I'll try to help you.
