### ISSUE TITLE
Flutter Web profile mode works but release does not

### ISSUE THREAD

**Issue by andreacioni** [flutterdata/flutter_data#172]
Hi Frank,

while building a project for web in release (`--release`) mode I noticed that the resulting application can't run and it displays the error below:

<img src="http://andysite.altervista.org/archive/Schermata_2022-07-27_alle_20.20.24.png" alt="drawing" width="200"/>

If I try to run the application in `profile` mode everything works as expected,

The really difficult thing is that nothing gets displayed into the console. I had to enable the Chrome debugger to stop the execution on exception. After digging into the code (dart and minified js) i trace back the cause of the exception in the `remoteAdapter` method of `Repository` ([here](https://github.com/flutterdata/flutter_data/blob/master/lib/src/repository/repository.dart#L16)) . The problem is related to a minification of the generic type T that, for example, if the type `T=Users` when minified became `T=minified:bs` . So when `remoteAdapter` is called, `null` is retrieved from the `_adapters` map because it contains `{'users': Instance ...}` 

I think that's maybe it's something more related to `dart2js` but maybe you have some advice on how to overcome this weird behavior. I try different ways but none of them seems to work.

Tested on:

- Flutter 3.0.5
- flutter_data_todos (latest)

**Comment by frank06** [comment]
I'm sorry to hear this. I always reluctantly supported Flutter web because of things like these.

A kind soul [submitted a PR](https://github.com/flutterdata/flutter_data/pull/152) and after a while it brought up several of these `toString on null` errors that were very difficult to debug and find.

@Skycoder42 by any chance would you happen to know what is causing this error?

Otherwise I suggest opening an issue on `dart2js` as the code you reference is perfectly valid Dart.

**Comment by frank06** [comment]
Could you find workarounds to turn your profile mode into release?

**Comment by Skycoder42** [comment]
Okay, so I do kinda now whats going on. When dart is compiled to JS in release mode, there are no guarantees given on how the types are named (kinda as if you would enable obfuscation in standard dart). This is not a bug but standard behaviour. I think the dart documentation even states to not use toString on typenames in JS somewhere (I found a lint: [avoid_type_to_string](https://dart-lang.github.io/linter/lints/avoid_type_to_string.html)). I do not know if you can disable minification for dart2js, but maybe adding "-O0" will help.

Other than that, the only workaround I can think of is to overwrite the `type` (and maybe even the `internalType`) of each repository for every data model and to explicitly specify a sensible type name.

@frank06 Another way to help from the library side could be to add a `DataHelper.defineTypeName<T>(String name)` to allow developers specify the type name globally in there, overwriting the default name generation - this would also help with reserver type names etc.  As the implementation of `getType` already uses an internal cache, this would be very easy to implement.

**Comment by andreacioni** [comment]
> Could you find workarounds to turn your profile mode into release?

Actually I started propagating the type to [initialize](https://github.com/flutterdata/flutter_data/blob/master/lib/src/repository/repository.dart#L25) totally replacing the `DataHelpers.getType<T>();` invocation in `_internalType` . That helped with the first point but then I saw that `DataHelpers.getType<T>();` is also used in other places as well. So maybe we should never use it without a `type ` parameter but at the moment I'm not sure if this is feasible in other places.

> I do not know if you can disable minification for dart2js, but maybe adding "-O0" will help.

That was my last attempt but it seems not supported yet the ability to pass parameters (according to this [issue](https://github.com/flutter/flutter/issues/99015) ). Even if there is this Dart [official package](https://pub.dev/packages/build_web_compilers) that seems to be helpful but I can't make it work during Flutter build .

**Comment by andreacioni** [comment]
> Another way to help from the library side could be to add a DataHelper.defineTypeName<T>(String name) to allow developers specify the type name globally in there, overwriting the default name generation - this would also help with reserved type names etc. As the implementation of getType already uses an internal cache, this would be very easy to implement.

That's a good point, I added the function you suggested in `DataHelper`:
```dart
static void defineTypeName<T>(String type) {
    _types[T] = type.decapitalize().pluralize();
  }
```

In main.dart I added:
```dart
void main() {
  DataHelpers.defineTypeName<User>("user");
  DataHelpers.defineTypeName<Todo>("todo");
  runApp(
    ProviderScope(
      child: const MyApp(),
      overrides: [
        configureRepositoryLocalStorage(clear: false),
      ],
    ),
  );
}
```

A little hacky but it works. We could use it but I think that the root cause to the error is to use `T.toString()` . As explained in this [other issue](https://github.com/dart-lang/sdk/issues/48337) it seems to be a bad practice even if the problem appears just on Flutter Web.

**Comment by frank06** [comment]
Thank you @Skycoder42 @andreacioni !

I thought I could take this opportunity to improve the internal types. There is no more runtime type resolving, everything is done during codegen. If you want to override a type use e.g.:

```dart
@DataRepository([JSONServerAdapter], internalType: 'todos')
class Task extends DataModel<Task> {
```

Can you let me know if this helped?

**Comment by andreacioni** [comment]
Thanks @frank06 ! I had no time to check the insight of the solution but if I use the `internalType` everything works just fine even on a Web release build.

**Comment by frank06** [comment]
That's great!

**Comment by boosey** [comment]
I have this same issue. I performed a 'flutter pub upgrade' and added the internalType to my DataRepository annotation, yet I still get this message. I cleared cache and cookies from my browser. Did I miss a step?

**Comment by andreacioni** [comment]
Did you run the `build_runner` after upgrading ?

**Comment by boosey** [comment]
I realized that just 5 minutes after I posted this, but I was not in front of my computer when I did so. It is working now. Thanks.
