### ISSUE TITLE
Question: How to store models with custom endpoint?

### ISSUE THREAD

**Issue by KoalityJustin** [flutterdata/flutter_data#175]
So I've implemented a custom endpoint per https://flutterdata.dev/docs/adapters/#custom-endpoints but I'm unsure of how to make these models stored locally. Right now it looks like this:
```dart
Future<List<DailyActivity>> getActivities(Map<String, dynamic> post) async {
  final headers = await defaultHeaders;
  final result = await super.sendRequest<List<DailyActivity>>(
    baseUrl.asUri / 'daily/create',
    body: post.toString(),
    headers: headers,
    method: DataRequestMethod.POST,
    onSuccess: (data, label) async {
      if (data != null) {
        final items = await deserialize(data);
        return onSuccess(items, label);
      }
      return onSuccess(null, label);
    },
  );

  return result ?? <DailyActivity>[];
}
```

Have a small deserialize tweak which is why I have this onSuccess handler. But these models are not stored locally anymore; was there a change in >1.4 that I need to make?

**Comment by frank06** [comment]
Did you find out? Is this still a problem for you?

**Comment by ArneSaknussemm89** [comment]
@frank06 Totally forgot to close this! No longer a problem, just had to change the `onSuccess` to work differently.
