### ISSUE TITLE
Migration issue: provider not fetching data with 1.3.4

### ISSUE THREAD

**Issue by danielnordh** [flutterdata/flutter_data#178]
When updating from 0.8.2 to 1.3.4 (and RiverPod 1.0.4), our `transactionProvider` no longer returns any data.

Previous:
```
HookBuilder(builder: (context) {
   final state = useProvider(watchTransactions());
   final transactions = state.model;

   if (state.hasException) {
      return Text(state.exception.toString());
   }
   if (transactions.length == 0) {
      return const Spacer();
   }
   return Expanded( ....);
}
```

Now:
```
HookConsumer(builder: (context, ref, child) {
   final transactions = ref.watch(transactionsProvider);

   transactions.when(
      loading: () => Spacer(),
      error: (error, stack) => Text('Oops, something unexpected happened'),
      data: (value) {
         if (value.length == 0) {
            return const Spacer();
         }
         return Expanded(...)
      }
}
```

But the `data` state is never invoked.
A breakpoint added to the _adapter function feeding the provider is never hit.

What should I be doing differently @frank06?

**Comment by frank06** [comment]
Hey Daniel, were you able to solve this?

**Comment by danielnordh** [comment]
Hi Frank, not yet.
I will give the migration another go in about two weeks after wrapping up some other work.
Would love to be in touch then. Please email the best contact details (your previous email bounced).
