### ISSUE TITLE
Relationships are not stored when HiveLocalAdapter is used

### ISSUE THREAD

**Issue by arkjedrz** [flutterdata/flutter_data#179]
1.4.6
I have a single "BelongsTo" relationship in my app, code excerpt:
```
@JsonSerializable()
@DataRepository([])
class Entry extends DataModel<Entry> {
  @override
  final int? id;
  final BelongsTo<EntryForm> entryForm;

  Entry({
    this.id,
    required this.entryForm,
  });
}

@JsonSerializable()
@DataRepository([])
class EntryForm extends DataModel<EntryForm> {
  @override
  final int? id;

  EntryForm({this.id});
}
```

It is working correctly for as long app is running, relationship information is missing after app restart though.
I noticed HiveLocalAdapter forbid storing relationships, this is due to [this line](https://github.com/flutterdata/flutter_data/blob/29fb76c504ef4167de7842f335bc09f5bb1e70d9/lib/src/repository/hive_local_adapter.dart#L188). Why is such limitation required?

**Comment by frank06** [comment]
Can you share how are you accessing the relationships?

`LocalAdapter` is internal, it shouldn't concern you. Relationships are stored in the graph.

You could compare what you are doing with https://github.com/flutterdata/flutter_data_todos which is an app where relationships work just fine.

**Comment by arkjedrz** [comment]
One thing I noticed - there's `@JsonKey(name: 'userId')` above `late final BelongsTo<User> user;`, which I didn't use. Is this JsonKey annotation crucial? Other than that I don't see differences.

**Comment by frank06** [comment]
`@JsonKey(name: 'userId')` is a `json_serializable` annotation and it is used for remote serialization. I don't think it relates to your problem.

`BelongsTo` relationships are working well in many of my projects. If you could share more code, or ideally the whole project, I might be able to help you out.
