### ISSUE TITLE
[Tutorial] Creating a new todo adds one with `id=null` and one with the remote id

### ISSUE THREAD

**Issue by ariejan** [flutterdata/flutter_data#180]
Hi, 

I'm following along with the tutorial, I've setup a Ruby on Rails REST back-end to store tasks.

When I create a new task, it's added to the list of tasks with `id=null`. A POST request goes out and my server responds with the created task (it's identical, but with an ID).

The list now shows _both_ a todo with `id=null` and one with `id=<int>`. For both `DataModel.keyFor()` returns the exact same value, so I kind of expected the item to be replaced instead of added.

Am I missing something here? Thanks for your help!

**Comment by frank06** [comment]
That absolutely looks like a bug. When I get a bit of time I will try to reproduce in https://github.com/flutterdata/flutter_data_todos (you could also there if you want).

Are you running `1.4.7`?

**Comment by frank06** [comment]
@ariejan Fixed. Let me know if it works for you

**Comment by ariejan** [comment]
@frank06 I can confirm this issue has been resolved. Thank you so much!
