### ISSUE TITLE
Failure on page reload

### ISSUE THREAD

**Issue by boosey** [flutterdata/flutter_data#182]
First load of my Flutter web app utilizing flutter_data works just fine. If I reload the page via the web browser,  I receive the following: 

``` 
[flutter_data] Box failed to open:
Expected a value of type 'Map<String, dynamic>', but got one of type 'LinkedMap<dynamic, dynamic>
```

I've searched but cannot find this issue answered anywhere.

**Comment by frank06** [comment]
I am reluctantly supporting Flutter Web because it's awful. Looks like a wrong cast, I'll try to reproduce soon.

**Comment by frank06** [comment]
I should be able to look at this next week. It would be great if you found a workaround in the meantime.

**Comment by boosey** [comment]
Any progress? I did find a workaround. I have to sync local storage all the time. For some reason, when syncing, it takes as long to hot reload as it does to stop and start the application in debug.

**Comment by frank06** [comment]
No, I couldn't look at this in detail yet.

What do you mean by "sync local storage all the time"? Can you share some code? Maybe that gives me a pointer to fix this faster.

**Comment by frank06** [comment]
#185
