### ISSUE TITLE
Re-enable web support, help needed

### ISSUE THREAD

**Issue by frank06** [flutterdata/flutter_data#185]
Flutter web is garbage but some people still want to use it.

Starting now I'm disabling Github Actions testing on web because I keep getting build failures with cryptic errors.

I have zero time for maintaining it. Anyone interested in helping out with web?

**Comment by maherjaafar** [comment]
@frank06 I can help out 😄

**Comment by frank06** [comment]
@maherjaafar that would be great. Tests are not passing on web and there's #182

**Comment by ariejan** [comment]
In my experience flutter has top-notch web support. However, sometimes starting and running a test in a (virtual) browser is a bit slower as expected. See #197 for details and updates to the test suite.

**Comment by frank06** [comment]
The upcoming local adapter is based on Objectbox which does not support web.
