### ISSUE TITLE
first-class offline support

### ISSUE THREAD

**Issue by frank06** [flutterdata/flutter_data#19]
Create an adapter or series of adapters with:

  - queue for read & write retries when server is unreachable (regardless of cause)
    - exponential backoff for retries
    - if "keeps loading for a while" (state.isLoading, from `data_state`), make it fail & retry

cc/ @jamesdixon

**Comment by frank06** [comment]
WIP https://github.com/flutterdata/flutter_data/blob/master/lib/src/adapter/remote/offline_adapter.dart

**Comment by frank06** [comment]
This looks great @jamesdixon  https://logux.io/

**Comment by jamesdixon** [comment]
@frank06 nice! Hadn't heard of Logux before

**Comment by rubgithub** [comment]
> WIP https://github.com/flutterdata/flutter_data/blob/master/lib/src/adapter/remote/offline_adapter.dart

Page not found

**Comment by frank06** [comment]
Closed in https://github.com/flutterdata/flutter_data/commit/17f08057d0027b3519ca40a3ab23fb75c1b25504

Exposes:
 - `offlineModels`
 - `saveOfflineModels()`
 - `forgetOfflineModels()`

 - Backoff or other usage of these primitives is left to clients to implement
 - Timeouts can easily be implemented via `connectionTimeout` on `http`, which throws a `SocketException` (can be changed with the upcoming `isNetworkError` adapter API)
