### ISSUE TITLE
Dependencies issues - Unable to add flutter_data

### ISSUE THREAD

**Issue by vd3d** [flutterdata/flutter_data#191]
Hi,

I use some other packages in my app and I'm unable to add flutter_data because of an old package reference.

Here is the error message:

Resolving dependencies...
Because i18n_extension 6.0.0 depends on analyzer ^5.2.0 and no versions of i18n_extension match >6.0.0 <7.0.0, i18n_extension ^6.0.0 requires analyzer ^5.2.0.
And because flutter_data >=1.5.1 <2.0.0-rc1 depends on analyzer ^4.7.0 and every version of visual_editor from path depends on i18n_extension ^6.0.0, flutter_data >=1.5.1 <2.0.0-rc1 is incompatible with visual_editor from path.

So, flutter_data depends on analyzer ^4.7.0 which is quite old, is there a way to upgrade it ?

Thanks

**Comment by amitamrutiya2210** [comment]
Remove analyzer: ^4.7.0 from pubspec.yaml file and add analyzer: ^5.3.1 dependency.
after try "flutter pub get" command in terminal

**Comment by frank06** [comment]
Correct, have you tried overriding dependencies? Can we close this one?

**Comment by Enhed** [comment]
`flutter pub get` does not let you install `analyzer` version higher than the one installed in the `flutter_data` package

**Comment by frank06** [comment]
@vd3d  I suppose "old" is relative as `analyzer 4.7.0` is just 3 months old.  That dependency will stay there for now as upgrading to `5.x` causes incompatibilities with common libraries when using the latest stable Flutter (`3.3.10`)

Which Flutter version are you running? Perhaps you can try downgrading `i18n_extension`?
