### ISSUE TITLE
Global initialization of repositoryInitializerProvider

### ISSUE THREAD

**Issue by musaffa** [flutterdata/flutter_data#198]
Currently repositoryInitializerProvider has be initialized in every page. Is it possible to initialize this provider globally in main.dart like [this](https://codewithandrea.com/articles/riverpod-initialize-listener-app-startup/) or in a parent node in the widget tree so that all the child nodes can access the ref.[repositories]?

**Comment by frank06** [comment]
What you are asking for is actually the way it's done. `repositoryInitializerProvider` only needs to be initialized once, typically in `main.dart`. See https://flutterdata.dev/docs/quickstart/

**Comment by musaffa** [comment]
Thanks. It has worked. I had to import main.data.dart in the children widgets which use ref.[repository].
