### ISSUE TITLE
is "has and belongs to many" possible?

### ISSUE THREAD

**Issue by mirozahorak** [flutterdata/flutter_data#206]
I do not see such in docs, is "has and belongs to many" possible?

**Comment by frank06** [comment]
Sure. What are you trying to accomplish?

**Comment by mirozahorak** [comment]
Thanks for the reply
basically the same functionality as in Ruby on Rails. 
f.e. when i have a project and users, than to one project belong many users. and at the same time One user belongs to many projects. There is a third, connection table, connecting these 2 together via project_id and user_id.

you can fine more info about such here
https://guides.rubyonrails.org/association_basics.html#the-has-many-through-association
and here
https://guides.rubyonrails.org/association_basics.html#the-has-and-belongs-to-many-association
