### ISSUE TITLE
Question: is it possible to get stream of model events?

### ISSUE THREAD

**Issue by andreystavitsky** [flutterdata/flutter_data#209]
I'm usig flutter_bloc and I want to listen to user's changes. How can I do that?

```
final repository = GetIt.instance.get<Repository<AppUser>>();

repository.watchOne(user.id) => _CastError (Null check operator used on a null value)
repository.watchOneNotifier(user.id) => _CastError (Null check operator used on a null value)
```

**Comment by frank06** [comment]
At some point I assumed clients all use Riverpod and stopped testing with other libraries like Provider, GetIt or bloc.

You could try `repository.remoteAdapter.watchOneNotifier(...)` but note that you will have to pass the model's `key` that you can obtain via `DataModel.keyFor(model)`.
