### ISSUE TITLE
app crashes when http request times out

### ISSUE THREAD

**Issue by jamesdixon** [flutterdata/flutter_data#21]
I'm not sure if this has to do with offline code specifically, but the app will crash if a network request times out.

I tested this by using Network Link Conditioner on my Mac (can also be used on your phone). I highly recommend using this to test offline as the '100% loss' setting is much different than wi-fi being on/off. It will simulate an actual shitty connection where you're still connected to the network but there is no response.

**Comment by frank06** [comment]
Fixed in 953904ac53acb1d1fff6f016dad110bc294c09d8
