### ISSUE TITLE
Bump deps to analyzer 5.0 possible?

### ISSUE THREAD

**Issue by mirozahorak** [flutterdata/flutter_data#211]
analyzer 4.7.0 is not compatible with riverpod_generator

Because riverpod_generator >=2.0.0 depends on riverpod_analyzer_utils ^0.1.0 which depends on analyzer ^5.0.0, riverpod_generator >=2.0.0 requires analyzer ^5.0.0.
And because flutter_data 1.5.5 depends on analyzer ^4.7.0 and no versions of flutter_data match >1.5.5 <2.0.0, riverpod_generator >=2.0.0 is incompatible with flutter_data ^1.5.5.

**Comment by frank06** [comment]
Released FD 1.5.6 with dependency upgrades
