### ISSUE TITLE
More deps incompatibilities when using riverpod packages

### ISSUE THREAD

**Issue by mirozahorak** [flutterdata/flutter_data#212]
flutter_data as of now is not compatible with  riverpod_generator and riverpod_lint because of dependencies.
Some issues can be solved by setting minimum required version of analyzer dependency to 5.4.0.

Because flutter_data >=1.5.6 <2.0.0-rc1 depends on analyzer ^5.6.0 and every version of custom_lint_core depends on analyzer >=5.4.0 <5.5.0, flutter_data >=1.5.6 <2.0.0-rc1 is incompatible with custom_lint_core.

And because riverpod_generator >=2.0.0 depends on riverpod_analyzer_utils ^0.1.0 which depends on custom_lint_core ^0.2.12, flutter_data >=1.5.6 <2.0.0-rc1 is incompatible with riverpod_generator >=2.0.0.

and also
Because flutter_data >=1.5.6 <2.0.0-rc1 depends on analyzer ^5.6.0 and custom_lint_builder >=0.2.0 depends on analyzer >=5.4.0 <5.5.0, flutter_data >=1.5.6 <2.0.0-rc1 is incompatible with custom_lint_builder >=0.2.0.
And because riverpod_lint >=1.1.0 depends on custom_lint_builder ^0.2.12, flutter_data >=1.5.6 <2.0.0-rc1 is incompatible with riverpod_lint >=1.1.0.

I have also contacted maintainers of custom_lint_core and asked to update deps.

**Comment by mirozahorak** [comment]
i have set analyzer dep version to   analyzer: ^5.4.0 and seems to pass.

**Comment by frank06** [comment]
Which Flutter version are you using? I might have to downgrade some dependencies

**Comment by frank06** [comment]
To use the latest in a Flutter 3.7.1 project I had to:

```dart
dependency_overrides:
  collection: ^1.16.0
  test_api: ^0.4.16
```
