### ISSUE TITLE
MONGODB CONNECTION

### ISSUE THREAD

**Issue by meladam20** [flutterdata/flutter_data#214]
Hello,
It's possible to use flutter_data and mongodb ? If yes, how ?

**Comment by frank06** [comment]
What have you tried?

**Comment by frank06** [comment]
`baseUrl` should point to where your server is running. If it's running on `http://localhost:3030` then put that.

**Comment by meladam20** [comment]
In my case, get and post are different url with express. Onliy adding "http://localhost:3030" can resolve my problem ? Can i get all tasks and put task only with this server url ?

**Comment by frank06** [comment]
Please read https://flutterdata.dev/docs/repositories/

You might need to override `urlForFindOne`, etc, but probably not.
