### ISSUE TITLE
data synchronization

### ISSUE THREAD

**Issue by meladam20** [flutterdata/flutter_data#217]
Hello,
When i can do update when i don't have connection but when internet coming, my update is delete by the distant data on mongodb.
How flutter data can send last update on json server when internet come back ?
Help my please.

**Comment by meladam20** [comment]
Hello, someone can help me please ?
when i add or update task in offline, how this new task can be send automatically on my json server when i am in online ?
How synchronization work exactly ?

**Comment by frank06** [comment]
https://flutterdata.dev/docs/offline/

For details you have the source code at your disposal.
