### ISSUE TITLE
LOCAL SAVING

### ISSUE THREAD

**Issue by meladam20** [flutterdata/flutter_data#220]
Hello,
after user registration, i want to user data to allow this iser to automatically login when he come back on application but my code doesn't work. the data are save locally but when i reload application with "hot reload" or "shift+cmd+F5", all data are delete. Help me please.

Here is my code : 

    final user = User(
        firstName: firstName.text,
        lastName: lastName.text,
        email: email.text,
        password: password.text);

    final userRegistered = await user.save(onSuccess: (a, b, c) async {
      final isUser = await ref.users.findAll(
          params: {'email': email.text, 'password': password.text},
          syncLocal: true,
          remote: true);
      for (var user in isUser!) {
        user.saveLocal();
        print('isUser save');
      }
    }
    });

**Comment by frank06** [comment]
I have little time to answer here. For these kind of requests please use Discussions.

I never tried FD on web but here are some ideas:
 - Do you know what `syncLocal` does? Are you sure that is not deleting your local models?
 - In `configureRepositoryLocalStorage`, make sure the `clear` argument is set to `LocalStorageClearStrategy.never` (should be the default but you can try)

Your use of `onSuccess` looks strange... not sure what are you doing with `a`, `b` and `c`. Simply await `user.save` and continue below.
