### ISSUE TITLE
Question About Structure of Library

### ISSUE THREAD

**Issue by kivo360** [flutterdata/flutter_data#221]
I noticed you put a lot of emphasis on using HTTP interfaces to interact with remote systems. After going around the world of possibilities, I've come to the conclusion that `flutter_data`, `prisma` and  drift (if you use it well). 

We aren't directly using HTTP (using Supabase which runs on postgrest). How would I add functions and relationships from a library like **Supabase** to an app like `flutter_data`. I'm primarily looking for something to manage the relationships between freezed models and instantly plug me into my use of Riverpod.  

`flutter_data` deals with relationships well (via raw HTTP calls)

I thought I'd override the primary functions, but I realize you have the app wired up in a complex manner as you're managing a repository. The relationships and watchers are lost on me. They're my priority as a feature. If I can figure it out, I'll be able to reduce further coding time by weeks (Codegen + LLMs lol)

**Comment by frank06** [comment]
The HTTP interface is the default for remote data access but it can be completely and transparently bypassed. I have successfully implemented a `FirestoreAdapter` in one project.

> flutter_data deals with relationships well (via raw HTTP calls)

Relationships is an orthogonal concept to the HTTP remote adapter. They will work with data sourced from any adapter.

> I thought I'd override the primary functions, but I realize you have the app wired up in a complex manner as you're managing a repository

Not sure I understand what you mean. Where do you see the complexity? You can easily override the primary functions.

> The relationships and watchers are lost on me. They're my priority as a feature.

Similar to streams, watchers are `StateNotifier`s and work as you would expect.

There is a medium-term plan to refactor the local storage and support Isar, and floor/sqlite in the longer-term, as well as the ability for anyone to implement a local storage strategy which is currently not possible.

**Comment by kivo360** [comment]
Can you provide the Firestore adapter? I'd really appreciate it. I'm a foreigner to this library. Seeing a full example would be extremely helpful for implementation.

**Comment by frank06** [comment]
Not really as it's proprietary code but I can share the rough structure to get you started:

```dart
mixin FirestoreAdapter<T extends DataModel<T>> on RemoteAdapter<T> {
  @override
  Future<List<Report>> findAll({
    bool? remote,
    bool? background,
    Map<String, dynamic>? params,
    Map<String, String>? headers,
    bool? syncLocal,
    OnSuccessAll<Report>? onSuccess,
    OnErrorAll<Report>? onError,
    DataRequestLabel? label,
  }) async {
    final db = ref.read(firebaseServiceProvider).db; // somehow get the Firestore DB
    final query = db.collection('xxx'); // can use `type`
    final snapshot = await query.get(...);
    return snapshot.map((qs) {
      final map = querySnapshotToJson(qs);
      return await adapter.deserialize(map).saveLocal();
    });
  }
}
```

And similar overrides for `findOne`, `save`, `delete`, etc. The rest of FD should work as expected
