### ISSUE TITLE
DataModel as mixin

### ISSUE THREAD

**Issue by andreacioni** [flutterdata/flutter_data#222]
Hi everyone,

I was wondering if there is a way to let `flutter_data` work with model that are defined in some other packages. I've imagined something like that:

`class A extends B with DataModel<A>` 

where `B` is model defined in another package. But since `DataModel` is a class and not a mixin that simply can't work.

I tried to find similar issues here on GitHub but the only referring to this argument was #165 . Was `DataModelMixin` introduced? Maybe with a different name?

**Comment by damienkaliop** [comment]
I'm interested too because I'm stuck in the same issue with generated models from GraphQL

**Comment by frank06** [comment]
- Renamed `DataModel` to `DataModelMixin`
 - Re-added `DataModel` as an abstract class mixing in `DataModelMixin`
 - This should not break anything, but make `DataModelMixin` available - see the `Library` model in tests for an example
 - **Important**: Models using the mixin MUST call `init()` after being initialized, this includes using `copyWith` in freezed classes

Try out that commit and let me know if it helps.

**Comment by andreacioni** [comment]
Hi @frank06 ,

just tried the new version (1.5.12) with the mixin and I can confirm that is seems to work reliably.

Great work and many thanks!
