### ISSUE TITLE
Hive will be deprecated soon

### ISSUE THREAD

**Issue by damienkaliop** [flutterdata/flutter_data#223]
Hi
Simon notified 3 days ago that he will soon mark Hive as deprecated (https://twitter.com/simcdev/status/1656830248955314176).
Have you heard about this?

What is the future of flutter_data? Will it still be maintained?
Do you already plan to switch to another solution?
Can we already use another key-value storage?

In the meantime, I will start to see if I can offer you a PR but I don't want to duplicate the work

**Comment by frank06** [comment]
Appreciate the heads up and offering a PR but it's quite complex to swap out the underlying local storage, unfortunately.  There's a plan to move to Isar (been playing around here https://github.com/flutterdata/yacht ) and make it easier to plug different implementations (floor, objectbox, etc)

**Comment by damienkaliop** [comment]
I understand
Nice to hear that action is already planned in this direction. Indeed if you switch to Isar and leave the key-value pair system, it will take a lot of work
I wish you all the courage you can and don't hesitate to call on the community if needed. We owe this to the open-source world

**Comment by damienkaliop** [comment]
Hi again @frank06 
It seemed to me that Hive would no longer be deprecated, but would see a new version.
Do you have any more information? And what about flutter_data?

**Comment by frank06** [comment]
Will be moving to Hive 4 soon! 

https://pub.dev/packages/hive/versions/4.0.0-dev.0

**Comment by frank06** [comment]
Working on it on the `v2` branch

**Comment by frank06** [comment]
Turns out Hive and Isar are too risky. I opted to build on Objectbox instead, work in progress

**Comment by frank06** [comment]
Update: FD 2.0 coming very soon with great features and performance!

Will share details later


https://github.com/flutterdata/flutter_data/assets/66403/8b963ded-81f1-4f77-b25e-9ca2457d459e

**Comment by ccfiel** [comment]
@frank06 when version 2 be release?

**Comment by frank06** [comment]
November or December, quite likely.
