### ISSUE TITLE
ability to flush local data store manually

### ISSUE THREAD

**Issue by jamesdixon** [flutterdata/flutter_data#23]
`FlutterData.init(baseDir, clear: true)` works when the app is booted but if you manually want to flush the store, say on a logout event, it doesn't seem there is a way to do that unless you manually do so with Hive.

**Comment by jamesdixon** [comment]
One of the problems with `clear: true` is that if the app was to crash or was killed in the background by the OS and then you reloaded the app and there is a shit connection, there is no data in the store to immediately load. This is a case where I'd rather leave data intact on startup and then manually flush it on logout. Thoughts?

**Comment by frank06** [comment]
It is already possible to manually clear local storage for a type:

```dart
await repository.localAdapter.clear();
```

`FlutterData.init(clear: false)` can be supplied to change this behavior. It is `true` by default while Flutter Data is in alpha releases, i.e. `< 1.0.0`.
