### ISSUE TITLE
Custom adapters Example with Appwrite

### ISSUE THREAD

**Issue by hortigado** [flutterdata/flutter_data#231]
Hello, could you implement flutter data with appwrite? If so, could you help me with an example that I can't find an example of how to use custom adapters?

**Comment by frank06** [comment]
Hi! I don't know what AppWrite is but I'm sure it's possible. Let me know what you've tried and maybe I can help

There are plenty of examples of custom adapters
 - https://github.com/flutterdata/flutter_data_json_api_adapter
 - https://github.com/flutterdata/tutorial
 - https://flutterdata.dev/articles/
 - test models (in the `test` folder)
