### ISSUE TITLE
Save() return Unhandled Exception

### ISSUE THREAD

**Issue by Velliane** [flutterdata/flutter_data#238]
Hi,

I use` remoteAdatper.save()` to save data got from API (using http request), but I got an `Unhandled Exception: Null check operator used on a null value` here: 

```dart
// ensure model is saved
 await localAdapter.save(model._key!, model);
```

Can you tell me what I'm doing wrong ?

Here my RemoteAdapter:

```dart
mixin PlacesAdapter<T extends DataModelMixin<T>> on RemoteAdapter<T> {

  @override
  Future<T> save(
    model, {
    bool? remote,
    Map<String, dynamic>? params,
    Map<String, String>? headers,
    Object? onSuccess,
    Object? onError,
    DataRequestLabel? label,
  }) {
    return super.save(model, remote: false);
  }
}
```

```dart
res.results.forEach((element) {
      ref.places.save(element, remote: false);
});
```

**Comment by frank06** [comment]
Is your model mixing in `DataModelMixin` or extending `DataModel`? The latter automatically initializes models, otherwise you need to `init` the model yourself before saving
