### ISSUE TITLE
offline adapters to sync offline data with remote ?

### ISSUE THREAD

**Issue by Ayesha009** [flutterdata/flutter_data#241]
How to write the offline sync logic using getit and not riverpod?

**Comment by frank06** [comment]
What have you tried?

**Comment by Ayesha009** [comment]
i have tried the offline initialisation in the docs. But it is in riverpods. How to use the offline retry provider in getit and not riverpods or provider?

This is the sample of code i found in the docs.
final initializerProvider = FutureProvider<void>((ref) async {
  // initialize FD
  await ref.container.refresh(repositoryInitializerProvider.future);
  
  // initialize other services
  
  // retry offline events
  final _sub = ref.listen(offlineRetryProvider, (_, __) {});
  
  // close offline retry subscription
  ref.onDispose(() {
    _sub.close();
  });
});
