### ISSUE TITLE
How to reset headers for authorization token for offline operations?

### ISSUE THREAD

**Issue by Ayesha009** [flutterdata/flutter_data#242]

**Comment by Ayesha009** [comment]
Can i try to call the offline operation, override the headers and then retry?

 OfflineOperation(
        adapter: repository.itemAdapter,
        label: item.label,
        httpRequest: item.httpRequest,
        timestamp: item.timestamp,
        headers: {'Content-Type': 'application/json'} &
            {
              'Authorization': 'Bearer ${preferencesHelper.token}',
            },
        body: item.body,
        onSuccess: item.onSuccess,
        onError: item.onError,
      ).retry();

**Comment by frank06** [comment]
That's right, you can query the offline operations, modify and retry manually

**Comment by alexdoan102** [comment]
@frank06  how does the above solution work with the new offlineRetryProvider  ?
 => https://flutterdata.dev/docs/offline/
