### ISSUE TITLE
How to query local data while offline

### ISSUE THREAD

**Issue by greenking19** [flutterdata/flutter_data#253]
I have two tables, one is User and the other is Todo
Due to design reasons, they are not related.
Due to design reasons, they are not associated, but the todo table has a userid field.
**User Table**
```dart
@JsonSerializable()
@DataRepository([JSONServerAdapter], internalType: 'user')
class User extends DataModel<User> {
  @override
  final String id;
  final String nickname;

  User({
    required this.id,
    required this.nickname,
  });
}
```
**Todo Table**
```dart
@JsonSerializable()
@DataRepository([JSONServerAdapter], internalType: 'to-do')
class Todo extends DataModel<Todo> {
  @override
  final String? id;
  final String title;
  final bool completed;
  final String? userId;

  Todo({
    this.id,
    required this.title,
    this.completed = false,
    this.userId,
  });

  Todo toggleCompleted() {
    return Todo(
      id: id,
      title: title,
      completed: !completed,
      userId: userId,
    ).withKeyOf(this);
  }
}
```
How to query local data when offline?
Similar to MySQL
```mysql
SELECT todo WHERE userId="xxx"
```

Another question is, I would like to know which data was created offline or created but not uploaded to the server. How do I need to search?

Sometimes I may need to clear all local data, can this be done?
This is the issue I encountered while using Flutterdata.
I hope to get your help.🙋
thank you！👨🏻‍💻

**Comment by frank06** [comment]
At the moment it's not possible to query, but I'm working on moving the backend from Hive to a database where queries will be possible.

For things created offline AND that were attempted to sync with a server but failed, try inspecting  `repository.offlineOperations`.  If you did not attempt to save they will not appear there

**Comment by alexdoan102** [comment]
@frank06  can you please show me example code of how to access repository.offlineOperations ???

**Comment by frank06** [comment]
@alexdoan102  `ref.users.offlineOperations`
