### ISSUE TITLE
Can you upgrade "uuid" package to latest version?

### ISSUE THREAD

**Issue by pdkcoder** [flutterdata/flutter_data#258]
Hi @frank06 
Hope you are doing well

I'm using intercom_flutter which requires uuid ^4.2.1.
While flutter_data is using ^3.0.4.
That causes the conflict, can you upgrade uuid?

**Comment by frank06** [comment]
can you try overriding the dependency for now?

**Comment by frank06** [comment]
No longer in v2, closing
