### ISSUE TITLE
How do i sort data on watchAll?

### ISSUE THREAD

**Issue by adsazad** [flutterdata/flutter_data#259]
I am using `watchAll`. and i want to sort data on date time field.

**Comment by frank06** [comment]
Easiest way is to sort in the `build` method.

Otherwise you can try overriding `watchAllNotifier` on an adapter and somehow use the `where` and `map` extensions (maybe `reduce` or `sort` are needed)

In FD 2.0 this will be much easier as we'll support queries with sorting
