### ISSUE TITLE
Questions on "auto retry" feature

### ISSUE THREAD

**Issue by pdkcoder** [flutterdata/flutter_data#262]
Hi @frank06 

I checked the change log and saw that auto-retry was added in v1.5.2 (7th Dec, 2022). Before that version, we implemented retry manually by using `repositoryProviders` to read the `offlineOperations`. In our case, we only need to retry 2 operations: `DataRequestType.save` and `DataRequestType.delete`, so we filter like below:

```
for (final operation in operations) {
        if (operation.label.kind == DataRequestType.save ||
            operation.label.kind == DataRequestType.delete) {
           await operation.retry();
        }
}
```

Questions: (We are using v1.6.0)
1. Is auto retry enabled by default? Do we need to configure anything?
2. If auto retry is enabled by default, is our code still working correctly? My colleague mentioned that the `offlineOperations` is empty.
What I suspect is if auto retry is handled by the library already, it will also clear the operations, that's why our list is empty, am I right?
3. Can we enable/disable auto retry?

**Comment by alexdoan102** [comment]
@thphuc  auto-retry in NOT enabled by default.  
 ==> you have to wire  it up like this: https://flutterdata.dev/docs/offline/ 
     ==> if you dont wire it up, there is no auto retry

BTW, can i get a sample code of:
`we implemented retry manually by using repositoryProviders to read the offlineOperations`

==> I'm trying to get a count of how many records are in the offlineOperations queue.

**Comment by thphuc** [comment]
Thanks @alexdoan102 for your answer

Do you mean this line of code? 
```
// retry offline events
 final _sub = ref.listen(offlineRetryProvider, (_, __) {});
```

@khduy1796 will share the part we wrote for the retry (please note that the code will be a sample, we can not share real code due to the NDA with our client)

**Comment by alexdoan102** [comment]
@thphuc  yes. its that main line:  (see attached file and screenshot)
![image](https://github.com/flutterdata/flutter_data/assets/73307/ad0968f5-ede9-437d-8c3a-7b4d2a2e3574)

**Comment by alexdoan102** [comment]
see attached example

**Comment by alexdoan102** [comment]
[main.dart.txt](https://github.com/flutterdata/flutter_data/files/14566154/main.dart.txt)

**Comment by frank06** [comment]
Did you manage to understand it? This is something that basically works in the projects but I know the offline API is far from ideal and would love to revisit at some point.

**Comment by frank06** [comment]
I'm dropping the auto retry feature in FD 2.0, clients will have to implement it however they see fit

**Comment by lucasdidur** [comment]
Any update on this?

**Comment by frank06** [comment]
@lucasdidur update on what, specifically?
