### ISSUE TITLE
Question: for offlineRetryProvider, how do i implement the callback function?

### ISSUE THREAD

**Issue by alexdoan102** [flutterdata/flutter_data#264]
for this line:
   final _sub = ref.listen(offlineRetryProvider, (_, __) {});

1.) how do i implement the callback function?  , (_, __) {}  => can i get an example?
   ==> just maybe get the number of items in the  _offlineOperations().toList() ???
     ==> i want to display the number of items in the retry queue/stream in the Ux.

2.) how do get a notification that the mobile is offline?
    => is there an notification event i can wire into?   
       => for example, show a message or turn the whole appbar.color = RED, when the mobile is offline
          ==> can you show me example of how to react to this event?

**Comment by frank06** [comment]
The offline API is pretty bad at the moment, sorry about that. No need to implement the callback function, if you want to get the items just access `offlineOperations`.

The offline operations are actual failures that get queued to be retried, FD knows nothing about network status and it doesn't matter. If you're technically "online" but with a very bad connection and can't POST a payload, in practical terms you were offline. There are libraries that you can use to help with UI indicators, that you could use in combination with `offlineOperations`
