### ISSUE TITLE
🙋🏻‍♂️ How to test Flutter models for JSON serialization?

### ISSUE THREAD

**Issue by musiolmarco** [flutterdata/flutter_data#268]
### Hello 👋

I am currently trying out the flutter_data package and it seems really awesome 🙌

However, there is one point where I am stuck. Unfortunately, there is no documentation for testing (at least I could not find one). My problem is as follows: I work with the json_serializable package and I always write unit tests for the `fromJson()` & `toJson()` methods to make sure that everything works. But since I implemented flutter_data, all of these tests fail. I guess I have to initialize something first to make everything work, but I wonder what is the best way to do this. The tests I am writing are looking something like this:

```
  test('Correct model gets returned from JSON data', () {
    Account account = Account(
      id: '64d41784b4fb905e40f22d8f',
      name: 'PayPal',
    );

    expect(
      Account.fromJson(
        readJson(jsonFileName: 'account_response.json'),
      ),
      account,
    );
  });
```

## Unfortunately, I get an error as soon as I try to create a model:
```
Null check operator used on a null value
package:flutter_data/src/utils/framework.dart 14:29               DataHelpers.getInternalType
package:flutter_data/src/model/data_model.dart 79:43              DataModelMixin._internalType
package:flutter_data/src/model/data_model.dart 87:45              DataModelMixin.init
package:flutter_data/src/model/data_model.dart 5:5                new DataModel
package:stableapp/src/features/accounts/data/models/account.dart  new Account
test/src/features/accounts/data/models/account_test.dart 10:23    main.<fn>
```

**Comment by musiolmarco** [comment]
Hey, a small update on this:

It is working now, by using and adjusting the `setUpFn` from your tests. However, the testing remains somehow very confusing and if I now need widgets tests that access ref...watchAll(), there are still errors that I have to fix myself.

Will there be proper documentation on tests in the future? Or is there perhaps a way to simply set up the whole thing?

Because, as already said, the package & idea behind it is very good, but unfortunately it is not very test-friendly. ☹️

**Comment by musiolmarco** [comment]
Or also maybe just a small tests example for the tutorial project would already be very great!🙂

**Comment by frank06** [comment]
I'm close to releasing FD 2.0 with lots of changes (including a revamped watcher test suite), I'm hoping it's simpler to understand now

**Comment by musiolmarco** [comment]
> I'm close to releasing FD 2.0 with lots of changes (including a revamped watcher test suite), I'm hoping it's simpler to understand now

All right, very cool🥳 Thanks for your work Frank🙌

Is it still worth implementing everything right now with the current version and update afterwards or are there very big changes to come, so that will be a lot of work to update everything?

**Comment by frank06** [comment]
Thanks! No big changes in terms of public API, as you wish.

Just pushed to `master` and a prerelease to https://pub.dev/packages/flutter_data/versions/2.0.0-rc2

**Comment by musiolmarco** [comment]
> Thanks! No big changes in terms of public API, as you wish.
> 
> Just pushed to `master` and a prerelease to https://pub.dev/packages/flutter_data/versions/2.0.0-rc2

Great, thanks @frank06! I guess I will close this issue then for now🙌
