### ISSUE TITLE
RemoteAdapter for GraphQL?

### ISSUE THREAD

**Issue by maciejdudek92** [flutterdata/flutter_data#269]
Could someone explain it to me like I'm a 5 year old how to create RemoteAdapter for GraphQL?

**Comment by frank06** [comment]
Let's start by: what do you want the API on FD to look like? How do your GraphQL queries look like?

**Comment by maciejdudek92** [comment]
I now that with GraphQL it would be harder to manage the api calls because of many queries that can be done, and many mutations, and for the first question I tried come up with something but for example User can have Add mutation, Update mutation and Delete mutation, and with this how to implement them in Adapter?
`
class GraphGLRemoteAdapter{}
mixin Query{}
mixin AddMutation{}

class UserRemoteAdapter extends GraphGLRemoteAdapter implements Query, AddMutation {
  @override // from Query
  String get query(String email) => '''
      query getUser(email: String) {
        user (email: $email ) {
          email
          firstName
          lastName
        }
      }'''';


  @override // from AddMutation
  String get addMutation(String email,String firstName,String lastName) => '''
    mutation AddUser(email: String!, firstName: String!, lastName: String!) {
      addUser(email: $email, firstName: $firstName, lastName: $firstName) {
          email
          firstName
          lastName
      }
    }
  }'''';

}

@JsonSerializable()
@DataRepository([UserRemoteAdapter])
class User extends DataModel<User> {
  final int? id;
  final String email;
  final String firstName;
  final String lastName;
  User({this.id, required this.email, required this.firstName,required this.lastName,});
}`

I have not experience with Mixins and extends so my example can be wrong here.

**Comment by frank06** [comment]
Should be much simpler, the adapter must be a mixin not a class:

```dart
mixin UserRemoteAdapter on RemoteAdapter<User> {
  @override
  Future<List<User>> findAll() async {
    // use here an instance of your graphql database
  }
  
  // same for save, etc
}
```

Remember to call `super()` when necessary. Look around the repos, there are some examples I think
