### ISSUE TITLE
Syncing issue when saving data models in Firebase background message handler

### ISSUE THREAD

**Issue by chris-wickens** [flutterdata/flutter_data#277]
When receiving a push notification I construct a message model from the notification data and attempt to save it locally so users can view the message next time they open the app even if they're offline. There are no errors when saving and I can confirm within the background message handler function that the message saved successfully to the message list, but when attempting to load that same message list after the user opens the app the message is no longer present. Only if the app has been force closed before it is reopened does the saved message appear in the message list, which suggests to me the main isolate isn't detecting changes made to models in other isolates. 

With shared preferences I have to call the reload method to reset the cache before the main isolate picks up the changes - is there a similar way to reload the FlutterData models? I tried disposing and reinitializing the repository which closed and re-opened the Hive boxes but that didn't work.

**Comment by frank06** [comment]
Unfortunately Flutter Data 1.6.x does not support multiple isolates. The new 2.x definitely does. I am still working on it
