### ISSUE TITLE
how to create adapters for same baseURL for all requests ?

### ISSUE THREAD

**Issue by Alvish0407** [flutterdata/flutter_data#278]
I am supposed to use baseURL for api call and supposed to pass url path in request body. How can I achieve it ?

**Comment by frank06** [comment]
Sorry, I don't understand your question. Can you share some code?

**Comment by Alvish0407** [comment]
> Sorry, I don't understand your question. Can you share some code?

my API call look like this

```dart
@override
Future<List<RemoteCategory>> getCategories({CancelToken? cancelToken}) async {
  return handleException<List<RemoteCategory>>(() async {
    final response = await httpClient.get(
      '/api/method/v1', // Same for all API calls
      cancelToken: cancelToken,
      data: {"type": "get_category"}, // API endpoint decided based on `type` param
    );

    return (response.data['data'] as List)
        .map<RemoteCategory>((e) => RemoteCategory.fromJson(e))
        .toList();
  });
}
```

So, How can I create adapters for this kind of requests ?

**Comment by frank06** [comment]
Please look around in the documentation, sample projects or open a discussion!
