### ISSUE TITLE
Override for urlForFindOne is scape string for using PostgREST

### ISSUE THREAD

**Issue by lucasdidur** [flutterdata/flutter_data#281]
Im trying to change the behavior of urlForFindOne, but does not work as spectated, instead of `?`, its replaced by `%3F`

```dart
  @override
  String urlForFindOne(id, Map<String, dynamic> params) {
    return '$type?id=eq.$id';
  }
```

`rest/v1/todos%3Fid=eq.7`

spectead

`rest/v1/todos?id=eq.7`

**Comment by InspectlyMads** [comment]
I had a similar issue with findAll for using pagination. I ended up making another adapter overriding the findAll method

`mixin PaginatedFindAllAdapter<T extends DataModel<T>> on RemoteAdapter<T> {
  //Implement paginated find all
  @override
  Future<List<T>> findAll({
    bool? remote,
    bool? background,
    Map<String, dynamic>? params,
    Map<String, String>? headers,
    bool? syncLocal,
    OnSuccessAll<T>? onSuccess,
    OnErrorAll<T>? onError,
    DataRequestLabel? label,
    int currentPage = 1,
    int? pageSize,
    List<T>? allItems,
  }) async {
    print("Fetching page: $currentPage");
    remote ??= true;
    background ??= false;
    syncLocal ??= false;
    params = await defaultParams & params;
    headers = await defaultHeaders & headers;
    allItems ??= <T>[];
    pageSize ??= getPageSize();

    params['currentPage'] = '$currentPage';
    params['pageSize'] = '$pageSize';

    label = DataRequestLabel('findAll', type: internalType, withParent: label);

   ...  
  }
}
`
