### ISSUE TITLE
Interwork with injectable

### ISSUE THREAD

**Issue by dricholm** [flutterdata/flutter_data#31]
Hello,

I found this package a few days ago and it looks really promising.

I have a question about using it with [injectable](https://pub.dev/packages/injectable). It is a code generator for [get_it](https://pub.dev/packages/get_it). I see get_it is mentioned in the documentation also.
I would like to use injectable's annotations with the classes of flutter_data. In the quick start it mentions you can use get_it. I guess that would be something like this:

```dart
Future<void> main() async {
  final baseDir = await getApplicationDocumentsDirectory();
  final manager = await FlutterData.init(baseDir);
  getIt.registerLazySingleton<Repository<User>>(
    manager.locator<Repository<User>>(),
  );

  WidgetsFlutterBinding.ensureInitialized();
  runApp(AppWidget());
}
```

Do you think there is a way to annotate Repository<User> with `@lazySingleton` for example? Or if injectable is a dependency flutter_data would use get_it + injectable as default/additional service locator? Unfortunately I don't know much about how build_runner works and if this would be even possible.

If there is a way could you please tell me? If it is currently not possible, can this somehow be implemented? I would also be interested in contributing.

Thank you!

**Comment by frank06** [comment]
Thank you for your kind words!  I'm not sure yet how this would work with injectable, as we need to place an annotation on generated code. Will try to have a look later.

**Comment by frank06** [comment]
Did you try https://github.com/Milad-Akarie/injectable#auto-registering-experimental ?

That should fix this issue.

**Comment by dricholm** [comment]
I tried auto registering now. Unfortunately it did not detect classes from generated files for me. I tried declaring an additional class: `class AuthRepository = $UserRepository with AuthAdapter;`, this can be registered, however this depends on LocalAdapter, which then also needs to be registered.

So I am manually registering flutter_data's classes before running the app:

```dart
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Init Flutter Data
  final baseDir = await getApplicationDocumentsDirectory();
  final manager = await FlutterData.init(baseDir);

  // Register Flutter Data's classes for get_it
  getIt.registerLazySingleton<Repository<User>>(
    () => manager.locator<Repository<User>>(),
  );

  // Run injectable's generated function for registering annotated classes
  configureInjection(Environment.dev);

  runApp(AppWidget());
}
```

Of course when running build_runner I get the warning: `[RegisterBloc] depends on [Repository] which is not injectable!`

I am not sure on which side this could be improved, flutter_data or injectable.

**Comment by frank06** [comment]
Let me try adding a `runs_before` to our FD's build. After that, Injectable should be picking up the whole code. If that doesn't work I think it should be improved on their side.

**Comment by dricholm** [comment]
That alone won't fix this if I understand it, please correct me if I am wrong somewhere. Flutter Data generates two classes for a Repository:

```dart
class _$UserRepository extends Repository<User> {}
class $UserRepository extends _$UserRepository with StandardJSONAdapter<User> {}
```

Even if injectable would pick up on these repositories it could not create them because of their dependency to `DataManager` (and `LocalAdapter` for now), which is created at runtime with `FlutterData.init()`.

Passing the get_it instance to `FlutterData.init()` would create a dependency on the package, right? I though of some solutions.

1. Add a register function as an optional parameter, which if set would also call it with the repository objects.
2. Going a little further and making an `abstract class Injector()` with `register()` and `locator()` functions a parameter for `FlutterData.init` and using the package's own version as default value. This way an injector/locator could be passed from outside.

Right now I am using it this way when using with a Bloc:

```dart
// auth_repository.dart
abstract class AuthRepository {
  // Contains register, login etc.
}

// user.dart
@JsonSerializable()
@DataRepository([StandardJSONAdapter, AuthAdapter])
class User extends DataSupport<User> {...}

mixin AuthAdapter on Repository<User> implements AuthRepository {...}

// register_bloc.dart
class RegisterBloc extends Bloc<RegisterEvent, RegisterState> {
  final AuthRepository _authRepository;

  RegisterBloc(this._authRepository);
}
```

This way testing the Bloc is easily done by passing in a Mock which implements AuthRepository. But I think the only way to use this is to manually register the Repository<User> as AuthRepository or $UserRepository as telling which type to search for could be hard for generated code between flutter_data and injectable.

There is one other thing I was thinking about, I am not sure if I should open a separate issue for it, so I will ask it here for now: Is there a reason to use `Repository<User>` instead of `$UserRepository`? The reason I am asking is because `$UserRepository` class contains mixin informations, so when I want to use an extension function I have to cast it to the mixin or `$UserRepository` first. If using `$UserRepository` that is not needed as it contains all the adapters annotated to it. Also is the `$` prefix used because it is a generated class?

**Comment by frank06** [comment]
Thank you for the detailed comment!  I'm busy with the upcoming 0.4.0 release but I'll have a look after that.

**Comment by frank06** [comment]
I'm going to make it such that if `GetIt.instance` is present, Flutter Data will register singletons for each repository. Including `Repository<User>` and `UserRepository`
