### ISSUE TITLE
flutterdata with bloc

### ISSUE THREAD

**Issue by drashoor** [flutterdata/flutter_data#33]
Is there any example how to use flutterdata with bloc?

**Comment by frank06** [comment]
For now here's an idea: https://flutterdata.dev/cookbook/adapters/#authentication-service

Will create a sample project soon.

**Comment by erkebek** [comment]
Would be very great to make a documentation with BLoC pattern. For now it seems very tightly coupled with Hooks and Riverpod.

**Comment by maherjaafar** [comment]
This link doesn't work https://flutterdata.dev/cookbook/adapters/#authentication-service
