### ISSUE TITLE
Guide for API post request

### ISSUE THREAD

**Issue by sooxt98** [flutterdata/flutter_data#35]
How to use this package to do a login request with post data param to API endpoint?
Am i going to create a userlogin repo can call save method?

**Comment by sooxt98** [comment]
I see, but is there any to store that token up and auto append to others repo request, so I no need to get the token and use as param Everytime? Something like middleware which auto append as bearer header or token param

**Comment by frank06** [comment]
https://flutterdata.dev/cookbook/adapters/#override-headers-and-base-url

**Comment by sooxt98** [comment]
@override
get queries {

}

Is this correct for query override?
this package seems awesome , I cone from laravel background and it just looks cool

**Comment by frank06** [comment]
Thank you!

For query parameters use `params` instead of `headers`.

**Comment by sooxt98** [comment]
Could you explain more on manager.locator, I'm not sure what's that and the service .Can we store the token straight into fluttet_data's hive?

**Comment by sooxt98** [comment]
![image](https://user-images.githubusercontent.com/13378059/83997645-70709580-a991-11ea-981c-07efcb9b8ace.png)
Is there any quick fix for this?

**Comment by frank06** [comment]
Try to initialize Hive earlier, and use `Hive.box()` which is sync inside `params`. I'll come up with a functional example soon.

**Comment by sooxt98** [comment]
@frank06 ahhh, okay; so how to init earlier and pass into this adapter >< The only way i know is to use GET_IT

**Comment by frank06** [comment]
I need to think how to make that work with a Provider-only setup.

Here is a workaround, but should work for you. The idea is to lazily fetch `params`, initializing them in an async method (in this case the one performing the HTTP call):

```dart
mixin BaseAdapter<T extends DataSupport<T>> on Repository<T> {
  @override
  String get baseUrl => 'https://your.api';

  Map<String, dynamic> _defaultQueryParameters;

  @override
  Map<String, dynamic> get params => _defaultQueryParameters;

  @override
  Future<R> withHttpClient<R>(onRequest) async {
    // we override withHttpClient to make sure
    // _defaultQueryParameters are (async) retrieved from
    // the Hive, then cached for all future calls
    final box = await Hive.openBox('carrot');
    _defaultQueryParameters ??= {
      'token': box.get('token'),
    };
    return super.withHttpClient(onRequest);
  }
}
```

No need to call `super.params` since it's empty.

**Comment by sooxt98** [comment]
But Overall concept I think It will cause performance issue, since it need to open hive box once when sending new request

**Comment by frank06** [comment]
No, just the first time. And you need to open your box at some point. As I said I will improve this API but this is what you can do right now.

**Comment by sooxt98** [comment]
Yaya I just worried about performace issue haha 😆 thanks for the work around

**Comment by vinidiktov** [comment]
This page is not available now https://flutterdata.dev/cookbook/adapters/#authentication-service

Where can I find the cookbook?

**Comment by frank06** [comment]
@vinidiktov check out https://flutterdata.dev/articles/ -- there are lots of examples there

**Comment by LennyLip** [comment]
> @vinidiktov check out https://flutterdata.dev/articles/ -- there are lots of examples there

Hello, thanks for the app. Where I can find "authentication-service" example now?
