### ISSUE TITLE
Support SQLite

### ISSUE THREAD

**Issue by rubgithub** [flutterdata/flutter_data#40]
It is possible extending Flutter Data to use SQLite? More precisely sqfentity  (https://pub.dev/packages/sqfentity#-readme-tab-).

**Comment by frank06** [comment]
Having SQLite as local backend is something I definitely want to do (once we have async relationships). Not sqfentity.

**Comment by rubgithub** [comment]
I'm not pro in Dart, but can you you guide me on firsts steps to start understand and maybe help in this feature?

**Comment by frank06** [comment]
Once I'm happy with an API design for async relationships (meaning async relationship model retrieval to support lazy Hive boxes and eventually SQLite) I'll let you know.  Have you gone through the code?

**Comment by rubgithub** [comment]
Not yet, but I read the documentation https://flutterdata.dev/.
I think I'm going to go through the code and try to understand.

Thanks 👍

**Comment by frank06** [comment]
Not happening anytime soon.
