### ISSUE TITLE
Possibility to overwrite the endpoint url?

### ISSUE THREAD

**Issue by DFelten** [flutterdata/flutter_data#44]
Is it currently possible to overwrite the endpoint for the request? I've got a class `PostDto`, but the endpoint is `/post`. 

As far as I can see the URL is built from the type and the BaseURL. But is it possible to overwrite the type? I don't want to rename the class because I work according to domain driven design and need a transfer object there.

**Comment by frank06** [comment]
Absolutely:

```dart
mixin URLAdapter on RemoteAdapter<PostDto> {
  @override
  String urlForFindAll(params) => '/post';
}
```

or something more generic:

```dart
mixin URLAdapter<T extends DataSupport<T>> on RemoteAdapter<T> {
  @override
  String urlForFindAll(params) => type.toLowerCase().replace('Dto', '');
}
```

More info here: https://flutterdata.dev/repository/#findall

**Comment by luketg8** [comment]
@DFelten did you go with the approach above? If so I'd be interested to hear how you adapted this library to fit with DDD/clean principles ie mapping the DTO to a domain entity whilst still taking advantage of the data repository functionality. 

I'm very interested in what this package has to offer but like you I'd rather have the data model separated and the repository returning a domain entity.

**Comment by frank06** [comment]
@luketg8 happy to help you make it work. What specifically is blocking you? Any code or architecture diagram you can share?

**Comment by luketg8** [comment]
@frank06 thanks for reaching out! Just wanted to say firstly that this package looks great :)

My issue really is that my code structure for each feature follows DDD principles, so basically they each have folders like this
Data
-    DTOs
-    Repositories
Domain
-    Entities
-    Repositories (Interfaces)
Application
-    BLoC/Provider/View Model etc
Presentation
-    Widgets

the issue really arises from the fact that the data models in this case are the DTOs but the business logic only deals with domain entities. This means that there would need to be a mapping step in the repository, both to and from domain entities, is this something that would be possible?

**Comment by frank06** [comment]
Flutter Data can be the core of your Data folder. Use the adapter pattern to fit this to your particular needs, such as your own `PostRepository` having a dependency on the FD-generated `Repository<Post>` (or `Repository<PostDto>`). See my answer above if you need to map your model names to URLs.

Does this help?

**Comment by luketg8** [comment]
@frank06 thanks for the suggestion!

I think that sounds like something that could work, I will look into it further 😃
