### ISSUE TITLE
FlutterData.init(baseDir, clear: false) crashes the App

### ISSUE THREAD

**Issue by gbenatti** [flutterdata/flutter_data#46]
When initializing FlutterData with clear equals false, throws:

E/flutter (30375): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, List<String>>' in type cast

at: (Repository.getBox)

final todoBox = await Repository.getBox<Todo>(manager, encryptionKey: encryptionKey);

Flutter doctor:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.5, on Microsoft Windows [versÃ£o 10.0.18363.900], locale pt-BR)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.47.0)
[✓] Connected device (1 available)

**Comment by frank06** [comment]
Thank you for the report! What Flutter Data version are you on, `0.4.1`?

**Comment by gbenatti** [comment]
Sorry the missing info:
  # state management
  provider: ^4.0.5

  # functional stuff
  freezed_annotation: ^0.11.0
  equatable: ^1.1.1

  # networking
  json_serializable: ^3.3.0

  # data
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  path_provider: ^1.6.7
  flutter_data: ^0.4.1

**Comment by gbenatti** [comment]
flutter version: 1.17.5

**Comment by gbenatti** [comment]
dart version 2.8.4
