### ISSUE TITLE
Is there any example how to use flutterdata with bloc?

### ISSUE THREAD

**Issue by khomsovon** [flutterdata/flutter_data#48]

**Comment by frank06** [comment]
Make your bloc depend on repositories.

Here's a small example: https://github.com/flutterdata/flutter_data/blob/8cf4a0ef77ac88c688e65414993c5d4df45b59a3/test/unit/repository/repository_test.dart#L105

I'll leave this open as I want to create an example with flutter bloc and/or cubit at some point.
