### ISSUE TITLE
The method '$UserModelRepository' isn't defined for the type 'DataManager'.

### ISSUE THREAD

**Issue by rubgithub** [flutterdata/flutter_data#52]
This is my first attempt with flutter_data, I'm getting this error on `main.data.dart`

The method '$UserModelRepository' isn't defined for the type 'DataManager'.
The argument type 'dynamic' can't be assigned to the parameter type 'Repository<User>'.

My goal is to use with Bloc
This is my code:

```
@freezed
@DataRepository([JSONAPIAdapter, UserURLAdapter]) //StandardJSONAdapter
abstract class User extends DataSupport<User>
    implements _$User {
  factory User({
    @override @JsonKey(ignore: true) int id,
    @JsonKey(name: 'my_token') @required String myToken,
  }) = _User;
  // ignore: unused_element
  User._();

  factory User.fromJson(Map<String, dynamic> json) =>
      _$UserFromJson(json);

  factory User.toJson(Map<String, dynamic> json) =>
      _$UserFromJson(json);
}

mixin UserURLAdapter on RemoteAdapter<User> {
  @override
  String get baseUrl => 'http://jsonplaceholder.typicode.com/';
}
```

**Comment by rubgithub** [comment]
VSCode users!

If after generating code you still see errors in your files, try reopening the project. This is not a Flutter Data issue.

**Comment by frank06** [comment]
@rubgithub Glad you found out! And hang tight I'm close to releasing `0.5.0`. It comes with breaking changes but a much better framework overall.
