### ISSUE TITLE
Generated class name different from the original

### ISSUE THREAD

**Issue by rubgithub** [flutterdata/flutter_data#55]
The file original name is `AuthConfigModel` but flutter_data generates `AuthconfigModel` inside main.data.dart

```
 i.registerSingletonWithDependencies<Repository<AuthconfigModel>>(
        () => _owner.ref.read(authconfigmodelRepositoryProvider),
        dependsOn: [RepositoryInitializer]);

```

> The name 'AuthconfigModel' isn't a type so it can't be used as a type argument.\nTry correcting the name to an existing type, or defining a type named 'AuthconfigModel'.

**Comment by frank06** [comment]
Yes, sorry, this is a bug that is already fixed in a local commit. I will push this as soon as I can.

In the meantime, could you manually change it to `AuthConfigModel` in the generated file?

**Comment by rubgithub** [comment]
I'm gonna change `AuthConfigModel ` and wait next update, thanks.

**Comment by rubgithub** [comment]
I was looking at source code, is this line that fix the problem?

`i.registerSingletonWithDependencies<Repository<${(c['name']).capitalize()}>>(`

> (removing .capitalize())

 `data_library_builder.dart`
