### ISSUE TITLE
Where's interceptor?

### ISSUE THREAD

**Issue by rubgithub** [flutterdata/flutter_data#56]
How can I use interceptor v0.5.0?
Previously was
`FutureOr<R> withResponse<R>(response, onSuccess) async {`

**Comment by frank06** [comment]
Yes, I'm still working on the 0.5.0 docs.

The new method is using the `sendRequest` API.

What exactly do you need to do?

**Comment by frank06** [comment]
This is one example:

```dart
  @override
  FutureOr<R> sendRequest<R>(Uri uri,
      {DataRequestMethod method = DataRequestMethod.GET,
      Map<String, String> headers,
      String body,
      onSuccess,
      onError}) {
    final _onError = (DataException e) async {
      if (e.statusCode == 401) {
        final _sessionService = sl<SessionService>();

        // TODO: need to figure a way to pop back to login route
        await _sessionService.logout();

        return null;
      }
      onError(e);
    };
    return super.sendRequest(uri,
        method: method,
        headers: headers,
        body: body,
        onSuccess: onSuccess,
        onError: _onError);
  }
```

**Comment by rubgithub** [comment]
Ok, I'll wait.
By the way, how can I override timeout?

```
mixin MyAdapter<T extends DataSupport<T>> on RemoteAdapter<T> {
@override
  Future<T> withHttpClient<T>(fn) {
    _httpClient.connectionTimeout = const Duration(seconds: 60);
    _ioClient = IOClient(_httpClient);
    return fn(_ioClient);
  }
```

**Comment by frank06** [comment]
```dart
mixin MyAdapter<T extends DataSupport<T>> on RemoteAdapter<T> {
@override
IOClient get httpClient {
    _httpClient.connectionTimeout = const Duration(seconds: 60);
    return IOClient(_httpClient);
  }
```

**Comment by rubgithub** [comment]
> ```dart
> mixin MyAdapter<T extends DataSupport<T>> on RemoteAdapter<T> {
> @override
> IOClient get httpClient {
>     _httpClient.connectionTimeout = const Duration(seconds: 60);
>     return IOClient(_httpClient);
>   }
> ```

0.5.1?

**Comment by rubgithub** [comment]
Waiting documetation update.

**Comment by rubgithub** [comment]
> 0.5.1.

I'm on 0.5.1 and do not notice any change, am I wrong?

**Comment by rubgithub** [comment]
> This is one example:
> 
> ```dart
> @override
> FutureOr<R> sendRequest<R>(Uri uri,
>     {DataRequestMethod method = DataRequestMethod.GET,
>     Map<String, String> headers,
>     String body,
>     onSuccess,
>     onError}) {
>   final _onError = (DataException e) async {
>     if (e.statusCode == 401) {
>       final _sessionService = locator<SessionService>();
>       await _sessionService.logout();
>     }
>     onError(e);
>   };
>   return super.sendRequest(uri,
>       method: method,
>       headers: headers,
>       body: body,
>       onSuccess: onSuccess,
>       onError: _onError);
> }
> ```
> 
> Although this might have features of 0.5.1.
> 
> I will be releasing everything very soon. If you could hold on until tomorrow or so, it will be much easier.

This one.

**Comment by rubgithub** [comment]
> Sorry, I'm not following. What change are you expecting? That `sendRequest` signature is part of `0.5.1`. Maybe an issue with VSCode?

I got it, thanks.
