### ISSUE TITLE
Injection warning

### ISSUE THREAD

**Issue by rubgithub** [flutterdata/flutter_data#57]
```
class MyBloc extends Bloc<MyBlocEvent, MyBlocState> {
  MyBloc(this._repo) : super(MyBlocState.initial());
final Repository<Todo> _repo;
```
`main`

```
  Directory _dir;
  configureRepositoryLocalStorage(
    baseDirFn: () => _dir.path,
  );
  final _dirName = await getApplicationDocumentsDirectory();
  _dir = await _dirName.create();
  _dir.deleteSync(recursive: true);

   GetIt.instance.registerRepositories(
     baseDirFn: () => _dir.path,
   );
   await GetIt.instance.allReady();
```

Although injection works fine, I'm getting this warning, Is there any way to get rid of this?

> [MyBloc] depends on [Repository] which is not injectable!
> Did you forget to annotate the above classe(s) or their implementation with @injectable?

**Comment by frank06** [comment]
Sorry, this is unrelated to Flutter Data.

It seems that Injectable does not work with classes already registered with GetIt?
