### ISSUE TITLE
Flutter Web compatibility

### ISSUE THREAD

**Issue by frank06** [flutterdata/flutter_data#6]
Most dependencies are web compatible, need to sort out #1

**Comment by Zedjones** [comment]
Is this still the case? I'm having issue on Flutter Web with the local storage using `path_provider` and `path_provider` only working on iOS and Android

**Comment by frank06** [comment]
You are right in that it does not work properly. Looking into it.

**Comment by frank06** [comment]
@Zedjones should work now in  dd5df97 . I need to fix a few other things before releasing `0.8.1`

**Comment by Zedjones** [comment]
Awesome, thanks! Yeah, sorry, `path_provider` actually just works on everything except for web, I think. Thanks for taking care of that quickly, looking forward to the next release.

**Comment by frank06** [comment]
`0.8.1` published

**Comment by Zedjones** [comment]
> `0.8.1` published

Thanks for the fast response and release, cheers!
