### ISSUE TITLE
LocalAdapter

### ISSUE THREAD

**Issue by rubgithub** [flutterdata/flutter_data#60]
Hi there!

How to set my model to work only with local data (hive)?

I'm doing this
`mixin LocalBaseAdapter<T extends DataModel<T>> on LocalAdapter<T> {}`

And my adapter:
`mixin TodoAdapter on LocalAdapter<TodoModel > {}`

builder error:
> Unsupported operation: Adapter `LocalBaseAdapter<dynamic>` MUST have a constraint `on` RemoteAdapter<TodoModel>

**Comment by frank06** [comment]
All models are **always** stored locally on Hive. You don't have to do anything. And no, you can't create a mixin on `LocalAdapter`.

Sorry for the delay in documentation, I was sick this week.

**Comment by frank06** [comment]
If you want to access the local instances, use `remote: false` on `findOne`, `findAll`, etc
