### ISSUE TITLE
FormatException: Not an instance of List.

### ISSUE THREAD

**Issue by rubgithub** [flutterdata/flutter_data#61]
This error started to happen after trying to use LocalAdapter  describes here (https://github.com/flutterdata/flutter_data/issues/60)
Don't know if it makes sense.

> [SEVERE] flutter_data:data_repository_builder on lib/models/auth_model.dart (cached): 
> FormatException: Not an instance of List.
> [SEVERE] Failed after 650ms

> lib/main.data.dart:31:95: Error: Getter not found: 'authModelRemoteAdapterProvider'.
>     final graphs = <String, Map<String, RemoteAdapter>>{'authModels': {'authModels': ref.read(authModelRemoteAdapterProvider)}};

v0.5.1

**Comment by rubgithub** [comment]
After weeks trying to find a reason for the error, I figure out that removing the import line of the object  `AuthModel` 
`import 'package:mypackage/..../auth_model.dart';``
And adding again   `CTRL+.` (control + dot)

I'm still getting some generator issues, sometimes I have to add imposts manually. 😥

**Comment by frank06** [comment]
Hey, I'm really sorry I couldn't get to this. Feel free to open another issue if you still have problems with the generator.
