### ISSUE TITLE
Support riverpod >0.10.0, state_notifier >0.6.0

### ISSUE THREAD

**Issue by ac130kz** [flutterdata/flutter_data#62]
Riverpod and state_notifier got several updates ([https://pub.dev/packages/riverpod/changelog](https://pub.dev/packages/riverpod/changelog), [https://pub.dev/packages/state_notifier/changelog](https://pub.dev/packages/state_notifier/changelog)), which were mostly bug fixes. Could you please update them to the latest versions?

**Comment by frank06** [comment]
Sure, I will get to that as soon as I can.

**Comment by frank06** [comment]
@ac130kz done
