### ISSUE TITLE
Data saved locally returns null

### ISSUE THREAD

**Issue by rubgithub** [flutterdata/flutter_data#65]
```
@freezed
@DataRepository([AuthAdapter, BaseAdapter])
abstract class TodoModel extends DataModel<TodoModel> implements _$TodoModel {
  factory TodoModel({
    @override @JsonKey(ignore: true) String id,
    String title,
  }) = _TodoModel;
  // ignore: unused_element
  TodoModel._();
```

`Data from API`
```
final _ret = deserialize(json.decode(response.body));
  final _model = _ret.model.copyWith(
	id: '1',
  );
```

`Saving locally`
```
  mixin AuthAdapter on RemoteAdapter<TodoModel> {
  ...
      await save(todoModel, remote: false);
```

My API only returns `title` so I'm ignoring `id` to avoid `null error (deserialize(json.decode(response.body));)`

If the field is tagged  with  `@JsonKey(ignore: true)` it returns null ( happens after restart).
If I query (` await findOne('1', remote: false);`) the same object without restart, the data returns correct `(id: 1)`.

**Comment by rubgithub** [comment]
I had to create a 'fake' data return (id) to my API to avoid this issue.

**Comment by frank06** [comment]
Correct, Flutter Data doesn't support ID-less entities at the moment.

**Comment by frank06** [comment]
An alternative solution would be to override `deserialize` and return a UUID as `id`

**Comment by rubgithub** [comment]
Ok, But it occurs with any data that has only in my model and doesn't in my json return, for example 
 ` @JsonKey(ignore: true) String dataCreated`
Is this the same as `id`? Do I have to override `deserialize`?

**Comment by thphuc** [comment]
@rubgithub did you solve this issue?

I am getting the same issue with "ignore: true" field(s). 

@frank06 do you have any suggestion?

**Comment by frank06** [comment]
@thphuc Could you please expand on the issue you are having and provide some code?

**Comment by thphuc** [comment]
Hi @frank06 

My issue was if I use "ignore: true" for any fields in my model (DataModel), the framework does not save those fields to local storage. 

However, I did the debug into the framework yesterday and found the solution.
Before saving the model, the framework calls toJson( ) method (under model). So what I need to do is add all ignore fields to the json. 

Thanks for your quick response @frank06
