### ISSUE TITLE
Set sendRequest timeOut

### ISSUE THREAD

**Issue by rubgithub** [flutterdata/flutter_data#69]
How to set a timeout by overriding `sendRequest`?

```
@override
  Future<R> sendRequest<R>(
    Uri uri, {
    DataRequestMethod method = DataRequestMethod.GET,
    Map<String, String> headers,
    String body,
    OnData<R> onSuccess,
    OnDataError<R> onError,
  }) {
```

**Comment by frank06** [comment]
I would try:

```
  @override
  http.Client get httpClient {
    final client = HttpClient();
    client.connectionTimeout = const Duration(seconds: 5);
    return client;
  }
```

If you need more fine-grained control you can probably override the `sendRequest` function, wrapping `super.sendRequest(...)` in a `Future.timeout`. I haven't tried it, but let me know how that goes.

**Comment by rubgithub** [comment]
I'm getting timeOut twice (after 5 seconds and after S.O timeout default) when `wrapping super.sendRequest(...)`:

>     return Future(() async {
>       await super.sendRequest(
>         uri,
>         method: method,
>         headers: defaultHeaders,
>         body: body,
>         onSuccess: onSuccess,
>         onError: _onError,
>       );
>     }).timeout(const Duration(seconds: 5), onTimeout: () async {
>       print('time out');
>...

The first option I'm getting  `A value of type 'HttpClient' can't be returned from function 'httpClient' because it has a return type of 'Client'.` Is this part of 'dart:io' package?
```
 @override
  http.Client get httpClient {
    final client = HttpClient();
    client.connectionTimeout = const Duration(seconds: 5);
    return client;
  }
```
