### ISSUE TITLE
Support Firebase

### ISSUE THREAD

**Issue by frank06** [flutterdata/flutter_data#7]
- Write adapters for Firebase
 - Example for Firebase Auth (like `SessionService`)

**Comment by grangoni** [comment]
Hello, 
Thanks for working in this.
Will this adapter work with Firestore (or RealTime DB)?

**Comment by frank06** [comment]
@grangoni I'm starting with Cloud Firestore and Firebase Auth

**Comment by grangoni** [comment]
Perfect! looking forward to it.

**Comment by grangoni** [comment]
Hi, are you still planning to share a new version of flutter_data  (with a Firebase adapter)?

**Comment by frank06** [comment]
Yes, I'm working hard and almost done redesigning an important part of the system. I need that before the Firebase adapter, but it's part of the short term plan.

**Comment by grangoni** [comment]
Good to read you're still working on the library (and fb adapter) and plan an update short term! 
I'll pospone a bit more the redesign of persistence management in my app and wait for the next release then. Thanks for the great work

**Comment by frank06** [comment]
Any particular pain points with the existing Cloud Firestore package that you'd like to see addressed in Flutter Data?

**Comment by ngoctranfire** [comment]
@frank06, I think an important pain point I would really like to see is handling of Firebase structures like GeoPoint and Sever Timestamp fields, which needs to be mapped correctly when translated from the server to the client side for consumption and use.

**Comment by frank06** [comment]
Thanks! I think that might have more to do with `json_serializable`, but I'll take it into account for sure

**Comment by frank06** [comment]
https://gist.github.com/Salakar/a36bd0902d7d0c705696da9318cf4e71

**Comment by frank06** [comment]
The core is now mature enough to fully support Firestore as an external adapter.

If you need this feature, please contact me for my consulting rates.

**Comment by frank06** [comment]
@amanxnanda sorry I missed your question! Yes, it absolutely can be used with Firebase.

I am currently working on a huge project that relies Flutter Data and (heavily) uses Firestore though a custom FD-adapter.

**Comment by NaagAlgates** [comment]
@frank06 , Thank you for working on this. Do you have any example for flutter_data with FirebaseAuth?

**Comment by frank06** [comment]
@NaagAlgates I don't have a standalone example as such but yes we use Firebase Auth with FD. What have you tried?
