### ISSUE TITLE
sendRequest Timeout

### ISSUE THREAD

**Issue by rubgithub** [flutterdata/flutter_data#71]
https://github.com/flutterdata/flutter_data/issues/69
I'm getting timeOut twice (after 5 seconds and after S.O timeout default) when `wrapping super.sendRequest(...)`:

>     return Future(() async {
>       await super.sendRequest(
>         uri,
>         method: method,
>         headers: defaultHeaders,
>         body: body,
>         onSuccess: onSuccess,
>         onError: _onError,
>       );
>     }).timeout(const Duration(seconds: 5), onTimeout: () async {
>       print('time out');
>...

The first option I'm getting  `A value of type 'HttpClient' can't be returned from function 'httpClient' because it has a return type of 'Client'.` Is this part of 'dart:io' package?
```
 @override
  http.Client get httpClient {
    final client = HttpClient();
    client.connectionTimeout = const Duration(seconds: 5);
    return client;
  }
```

**Comment by frank06** [comment]
You need to wrap it in a `dart:io` client, like `return IOClient(client);`
