### ISSUE TITLE
Using flutter_data without provider seems to be outdated

### ISSUE THREAD

**Issue by rfuerst87** [flutterdata/flutter_data#72]
I was trying to get flutter_data running without provider. https://flutterdata.dev/cookbook/configure/ seems to be outdated. `FlutterData.init()` doesn't seem to exist anymore. Also auto-generated code in `main.data.dart` seems to be tightly coupled to provider. Is it still a thing to use flutter_data without provider? If yes, how?

**Comment by andreacioni** [comment]
How are you plannig to manage states? I saw the [ToDo](https://github.com/flutterdata/flutter_data_todos) example and there you can find an example using [Riverpod](https://pub.dev/packages/riverpod).

**Comment by rfuerst87** [comment]
I was trying to build a quick prototype using BLoC. According to the readme this should be possible without much hassle. It just seems like the docs are outdated. Maybe I give riverpod a shot as well. Anyway I was wondering whats currently supported and whether it would be possible to update docs.

**Comment by andreacioni** [comment]
By now looking through the code seems to be the only way to understand how to work with this awesome library. I'm waiting too for the updated docs 🤩

**Comment by rubgithub** [comment]
I'm using with BLoC+freezed+injectable+getIT
This is my initial configuration:

```
 Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  Directory _dir;
  configureRepositoryLocalStorage(
    baseDirFn: () => _dir.path,
    //clear: false,
  );
  final _dirName = await getApplicationDocumentsDirectory();
  _dir = await _dirName.create();

  getIt.registerRepositories(
    baseDirFn: () => _dir.path,
  );
  await getIt.allReady();
...........
```

`Model`

```
@freezed
@DataRepository([TodoAdapter, BaseAdapter])
abstract class TodoModel extends DataModel<TodoModel> implements _$TodoModel{
```

**Comment by rfuerst87** [comment]
Hi @rubgithub, thanks for sharing an example. I'm currently doing some tests with riverpod, but the version pub.dev seems to be outdated as well... Are there any plans updating the package and documentation?

**Comment by frank06** [comment]
@rfuerst87 have a look at https://github.com/flutterdata/flutter_data_setup_app – that should be up to date! There are examples for Provider, Riverpod and GetIt.

Sorry for the delay in updating the docs. I'm super busy at the moment but I'll get to it. They are 70% done.

In addition I had an issue with pub.dev because Google kicked me out of my account. Use git for the latest versions. I will find a way to get back to pub.dev, but not now.

Also thanks for the kind words about this library. It will get better (using it in several apps)

**Comment by andreacioni** [comment]
If it may help someone, here is how you could work with the most recent version of this library even if it isn't published on pub.dev (yet):

1. Git clone/download the repository
1. Place it wherever you want and set the `pubspec.yaml` accordingly (below is mine, I placed flutter_data on the root folder of my project):
```yaml
dependencies:
  ...
  flutter_data: 
    path: ./flutter_data
```

**Comment by frank06** [comment]
Might be even easier to:

```yaml
dependencies:
  ...
  flutter_data:
    git:
      url: https://github.com/flutterdata/flutter_data.git
      ref: 0.5.9
```

**Comment by frank06** [comment]
@rfuerst87  I think you should even be able to get the repos without any DI library. There's a tiny example of how to pass a repo into a bloc in the tests.

Are all your questions answered? Can we close this issue?

**Comment by rfuerst87** [comment]
@frank06 yes thank you. Keep up the good work!
