### ISSUE TITLE
Type mismatch in event keys and id

### ISSUE THREAD

**Issue by andreacioni** [flutterdata/flutter_data#73]
I'm having problem while using a Repository for an API that exposes resource type with a dash (like: /api/v1/_shopping-lists_).
I did some researches and I found that this check will never be passed: 
https://github.com/flutterdata/flutter_data/blob/9e0b37d17944156700bca5f559d127b92ea54589/lib/src/repository/remote_adapter_watch.dart#L53

It seems that _keys_ in the event are generated without taking into account the _type_ althougth I overrided the _type_ getter using the adapter mixin:
```dart
@override
String get type => 'shopping-lists';
```

If I use debugger I always see keys like that: `shoppingLists#as74bd41` (the random generated one). Could you please advise me If I missunderstood something?

Thank you very much!

**Comment by frank06** [comment]
Sure, the type is fine like that.

In your adapter, use `urlForFindAll` and others to override the URL:

```dart
  @override
  String urlForFindAll(Map<String, dynamic> params) => type.dashCase;

  @override
  String urlForFindOne(id, Map<String, dynamic> params) =>
      '${type.dashCase}/$id';

  @override
  String urlForSave(id, Map<String, dynamic> params) => '${type.dashCase}/$id';
```

where

```dart
extension StringExtension on String {
  String get dashCase {
    return split(RegExp('(?=[A-Z])')).join('-').toLowerCase();
  }
}
```

I agree that this could be more elegant, but it should work for now.
