### ISSUE TITLE
relationship name can only be named the camelCased version of the relationship type

### ISSUE THREAD

**Issue by jamesdixon** [flutterdata/flutter_data#74]
For example, if you have `HasMany<InspectionService>`, it must be named `inspectionServices` or else the relationship won't be properly populated.

Attempted to use `@JsonKey(name: 'inspectionServices') HasMany<InspectionService> services` but this resulted in the following error:

![image](https://user-images.githubusercontent.com/110114/98137809-a30ab580-1e7f-11eb-975b-c221dc470b56.png)

**Comment by frank06** [comment]
Fixed
