### ISSUE TITLE
Stuck in isLoading state if findAll returns an empty list

### ISSUE THREAD

**Issue by andreacioni** [flutterdata/flutter_data#75]
It seems that if there are no data returned by the findAll method (empty list) the `DataStateBuilder.builder` function _state_ parameter will never be called with `isLoading == false` and that results in infinite loading screen. No problems were detected if there is at least one element returned by the forementioned method.

I'm able to provide you more details if needed, thank you!

**Comment by frank06** [comment]
Hey @andreacioni absolutely, I ran into that issue as well. I hope to get to it soon. Thanks for reporting it.

An **untested** workaround would be (in `remote_adapter_watch.dart`)

```
          notifier.data = notifier.data.copyWith(isLoading: true);
          final models = await _future;
          notifier.data = notifier.data.copyWith(isLoading: false, model: models);
```

**Comment by andreacioni** [comment]
Perfect, it works! I'm trying to undestarnd why this solution couldn't replace the line: https://github.com/flutterdata/flutter_data/blob/d802ab727279a76aeedc6dd163065d27d703c528/lib/src/repository/remote_adapter_watch.dart#L82

Because your suggested solution seems to be the most understandable. In fact when the future resolves successfully you can tell to the listeners that your data is ready to be consumed. Maybe are you planning to change/update the incoming data in order to merge local and remote changes?

**Comment by frank06** [comment]
State is updated through the graph (via `DataGraphEvent`s).

As the HTTP request is resolved, the deserialization mechanism will save updates to local storage and trigger events. Without resources to deserialize, the updates were never triggered.

I fixed it with a new event to ensure the state gets updated with `isLoading=false`.

Let me know if that works for you:

```
  flutter_data:
    git:
      url: https://github.com/flutterdata/flutter_data.git
      ref: 0.5.12
```

**Comment by andreacioni** [comment]
Just tested, and yes, it works!
