### ISSUE TITLE
support queries/filters

### ISSUE THREAD

**Issue by frank06** [flutterdata/flutter_data#76]

**Comment by frank06** [comment]
Implemented `filterLocal`

**Comment by frank06** [comment]
`filterLocal` was removed in favor of the notifier `where` extension, this is used to filter models that pass through the notifier. For example:

```dart
  @override
  DataStateNotifier<List<Inspection>?> watchAllNotifier({
    bool? remote,
    Map<String, dynamic>? params,
    Map<String, String>? headers,
    bool? syncLocal,
    String? finder,
    DataRequestLabel? label,
  }) {
    return super
        .watchAllNotifier(
          remote: remote,
          params: params,
          headers: headers,
          syncLocal: syncLocal,
          finder: finder,
          label: label,
        )
        .where((i) => i.isVisible);
  }
```

Since at the moment FD uses a regular Hive box for persistence (which keeps all values in memory), use `findAll` and filter what you need in Dart.

**Comment by Nikhileshwar96** [comment]
Thanks @frank06 ,
I'll continue using the findAll now.

**Comment by frank06** [comment]
As long as a Hive regular box is local storage no, because it makes no sense. If we incorporate Isar then sure, its query mechanism will be exposed for clients to use

**Comment by Nikhileshwar96** [comment]
Ok, I understand. Thanks @frank06
