### ISSUE TITLE
How to deal with offline/online connection states

### ISSUE THREAD

**Issue by andreacioni** [flutterdata/flutter_data#77]
Hi Frank! I've set up everything with the latest version of `flutter_data` and `flutter_data_state` and all the stuffs work pretty well (some refinement to be done yet). Now I'm looking for a way to handle offline/online states, I read all the docs and the tutorials you made but it's not completely clear, for me, how to deal with them.

Let me explain better. From the first time I used this library I wondered that the online/offline support would work "_automatically_" and in case of a unavailable/unstable connection the underlying mechanism would make all work in the same manner (the user will receive the cached view of the resources). Now I'm seeing that this is not the behaviour. If I turn off the WiFi and reload (with a `RefreshIndicator` component) an exception raise causing the `notifier.hasException` to be `true`.

I'm probably using your libary in a wrong way. It's up to the user to decide what data source to use with a flag, maybe the `remote` in watchAll/wathOne ?

**Comment by frank06** [comment]
Correct, for now you can play with `remote: false` and the `shouldLoadRemoteAll`, `shouldLoadRemoteOne` callbacks.

When I published the docs I was about to finish the `OfflineAdapter` but got sidetracked and never really got to finish it. It's still in the plans. The new docs are 80% there and still have to get to them. I apologize for the delays and confusion.

That said, the primitives are there to make this work offline.

**Comment by frank06** [comment]
I'll leave this issue open as a reminder. In any case, feel free to ask more questions.

**Comment by frank06** [comment]
FWIW I regained access to pub.dev so you can simply `flutter_data: ^0.5.14` in your `pubspec.yaml` from now on

**Comment by andreacioni** [comment]
Just a wondering, have you ever thougth to adopt a different behaviour for the offline adapter? I mean, you could always return the cached version and then, silently, make a remote call that will eventually trigger a rebuild. This may be the default behaviour and the `remote` parameter could be used to force the data source to use.

It's an idea but I think it could help the majority of the users, let me know your thougth!

**Comment by frank06** [comment]
That *is* the default behavior.

What do you mean by "force the data source to use"?

If you want pure offline, you can pass `remote: false` to every single call. Or otherwise override `shouldLoadRemoteAll` and return `false` (or implement your own strategy)

**Comment by andreacioni** [comment]
Ok, maybe I'm missing something. Looking at the `remote_adapter.dart` file I see:

```dart
  Future<List<T>> findAll({..., bool remote=true}) async {
    [...]

    if (!shouldLoadRemoteAll(remote, params, headers)) {
      final models = localAdapter.findAll();
      [...]
      return models;
    }

    return await sendRequest<List<T>>(...);
  }
```
This method is called by the notifier.watchAll(remote: true/false) so with the remote parameter you are choosing the data source (with `remote==false` you look for data on local and otherwise you go online). This logic got drived from the user that has the control to choose when to contact the remote REST API instead of the local storage.

What I tried to suggest is something different. I'm thinking about a `findAll` function like that (simplified, exeption handling skipped):
```dart
  Future<List<T>> findAll({..., bool remote=true}) async {
    [...]

    final models = localAdapter.findAll();
    [...]
    //Fire an HTTP request and don't wait for it to resolve. When it will resolve (in the optimistic case) the graph will
    // be rebuilt accordingly. If it will fail you could catch the exception and log it.
    sendRequest<List<T>>(
      baseUrl.asUri / urlForFindAll(params) & params,
      method: methodForFindAll(params),
      headers: headers,
      onSuccess: (data) {
        return deserialize(data, init: init).models;
      },
    );
    return models;

  }
```
With this setup user will always have a faster feedback and after a while, if some online updates occurred, they will be reflected to the UI.

**Comment by frank06** [comment]
From what I understand, the behavior you want is provided by `watchAll`

**Comment by andreacioni** [comment]
You are rigth, I was misled by another problem (?), sorry. Suppose this scenario:

1. First application startup: no local data & remote data available (user reinstall the application), flag `clear: false`
1. Internet connection available
1. Data will be downloaded and displayed correctly, everything's fine. **No updates on data performed**.
1. User close app
1. Internet connection will become **unavailable**
1. User open app and **no data displayed**

In this scenario I expected data to be available even after the first run but they weren't.

**Comment by andreacioni** [comment]
I've found out the problem, it was a deserialization issue not related to this library but that was really hard to find. It was about an uncaught exception raised in HiveLocalAdapter.read():

https://github.com/flutterdata/flutter_data/blob/221333e46b24f1d9f4e66b3d8d0483a36cc29487/lib/src/repository/hive_local_adapter.dart#L158

```
Unhandled exception:
type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>' in type cast
```

Could be an idea to add a log of the error/warning here?

https://github.com/flutterdata/flutter_data/blob/221333e46b24f1d9f4e66b3d8d0483a36cc29487/lib/src/repository/hive_local_adapter.dart#L36

Probably there will be more people that will face this problem.

**Comment by frank06** [comment]
I'm not sure why that would happen. How does your data model look like?

**Comment by andreacioni** [comment]
In my case I've a field in an object that holds a list of nested objects like that:

```json
{
    "id": "5fa7d13c02d6fda71c3699cd",
    "elements": [
        {
            "item": "5f5fa26871a7241d7f51a8e8"
        },
        {
            "item": "5f934ad6c4c31f8b3cc4f8c3"
        }
    ],
}
```

I had to add the `@JsonSerializable(anyMap: true)` as a temporary workaround to get it work.

**Comment by frank06** [comment]
Okay. Does it work as an embedded map?

If `Element` is a data model, the issue with that payload is that `elements` have no `id` attribute.

**Comment by andreacioni** [comment]
Ok I understand, actually it is a data model and I would like to keep it unchanged (I don't like to work with plain embedded map), however the `anyMap` flag it's curently a good compromise.
