### ISSUE TITLE
[provider] The method 'watchAll' was called on null

### ISSUE THREAD

**Issue by andreacioni** [flutterdata/flutter_data#79]
Since the first time I've used this library I'm experiencing a weird problem: it seems that repositories aren't available rigth after the application start up causing this exception:

```
The method 'watchAll' was called on null.
Receiver: null
Tried calling: watchAll()
```

After a while, when the repository become available, the view gets refreshed and everything works as expected.

If I use debugger I clearly see that at first run this call: `context.watch<Repository<Todo>>()` resolves to `null`.

My setup:
-  `provider`
- `flutter_data` (v0.5.16) 
-  `flutter_data_state`(v0.3.1)

**Comment by andreacioni** [comment]
After some researches I've found out that this issue is related to the presence in the widget tree of a FutureProvider without `initialData` provided. When the widgets tree was initially built no repository is available yet and `watchAll` can't be called.  When the future resolves all the repository become available and the problem's gone.

One workaround could be to show up some loading indicator when `context.watch<Repository<Todo>>() ` is `null` but maybe there is a smarter way to deal with it.

**Comment by frank06** [comment]
How are you initializing your app?

Here's an example with Provider, Riverpod and GetIt: https://github.com/flutterdata/flutter_data_setup_app
