### ISSUE TITLE
Support GraphQL

### ISSUE THREAD

**Issue by frank06** [flutterdata/flutter_data#8]

**Comment by frank06** [comment]
https://hasura.io/

**Comment by arpitjacob** [comment]
GraphQL integration would be amazing, I use Hasura for all my projects.

**Comment by chimon2000** [comment]
Hasura & faunadb would be extremely nice

**Comment by frank06** [comment]
Happy to implement it as paid work! Let me know if interested

**Comment by chimon2000** [comment]
@frank06 is there any desire to still add GraphQL support?
