### ISSUE TITLE
JsonKey for the class name

### ISSUE THREAD

**Issue by kevin4dhd** [flutterdata/flutter_data#84]
I have a class called User, and the rest api is www.api.com/user, but using watchAll it calls www.api.com/users, how do I fix it?

**Comment by frank06** [comment]
You have to override `urlForFindAll` in your adapter.

Please read the docs: https://flutterdata.dev/repository/ and https://flutterdata.dev/repository/adapters/

There might not be 100% up to date, but you will understand how Flutter Data works.

**Comment by kevin4dhd** [comment]
Thank you very much, I have achieved it, one last question not to create another issue, is it possible to change the data type of the id? I'm working with mongo, sorry for so many questions
![image](https://user-images.githubusercontent.com/22886367/102826537-db723e80-43ae-11eb-81e6-0a9c0464dc2c.png)

**Comment by frank06** [comment]
Yes, it's definitely possible. Is your ID a `String`? Try it out

**Comment by kevin4dhd** [comment]
Thanks, what a fool I was, I had put a string with the lowercase S
