### ISSUE TITLE
override type

### ISSUE THREAD

**Issue by kevin4dhd** [flutterdata/flutter_data#85]
Hello, it's me again, I hope you don't mind that I ask so many questions, I'm trying to change the name of Type, in the documentation it indicates this

// or even
@override
String get type => 'USERS';

pero al usarlo ahora, parece que cambio el codigo fuente que me sale esto.

![image](https://user-images.githubusercontent.com/22886367/102943321-a97fdb80-4485-11eb-8612-06da3b346b28.png)

Cual es la nueva forma, lo necesito porque en relationshipsFor, el type me sale roles, pero la api rest me devuelve "role", si pudieras subir la documentacion al 80% estaria muy agradecido, el 20% se puede esperar, pero es peor tener una documentacion antigua ahora mismo

![image](https://user-images.githubusercontent.com/22886367/102943365-c74d4080-4485-11eb-98cc-c91b7a4e28d7.png)

**Comment by frank06** [comment]
Yes, I will do my best to update the docs but I'm very busy right now.

Do not override `type`. Use `urlForFindAll` and `urlForFindOne`
