### ISSUE TITLE
Failed assertion: boolean expression must not be null

### ISSUE THREAD

**Issue by chrallard** [flutterdata/flutter_data#86]
Unable to run `flutter packages pub run build_runner build`. The build fails with the error: 

```
Failed assertion: boolean expression must not be null 
[SEVERE] flutter_data:data_repository_builder on lib/src/data/models/user.dart:
```
This error is repeated for all of our Flutter Data models.

Versions:
```
Flutter 1.25.0-8.3.pre (latest on beta channel)

environment:
  sdk: ">=2.7.0 <3.0.0"

flutter_data: ^0.5.17
flutter_data_json_api_adapter: ^0.1.7
```

**Comment by frank06** [comment]
@chrallard A few questions:

Is `0.5.20` the resolved Flutter Data version on `pubspec.lock`?

Could you please show me your `user.dart` model? Or any model that makes the builder fail?
