### ISSUE TITLE
remove provider & get_it

### ISSUE THREAD

**Issue by frank06** [flutterdata/flutter_data#89]
Will only support Riverpod from here on

**Comment by rubgithub** [comment]
Hi there, does this mean that I won't be able to register my repositories through extension method?
```
  getIt.registerRepositories(
    baseDirFn: () => _dir.path,
  );
```
If yes, It'll have another possibility?

**Comment by frank06** [comment]
I need to check but the idea is to provide recipes without having to directly support GetIt

Have you been able to upgrade? How are you finding Flutter Data?

**Comment by rubgithub** [comment]
Yes, I've upgraded to 0.6.3
I'm very satisfied, Flutter Data, it is going pretty well for me.

By the way
I saw that `OnDataError onError` now returns `FutureOr<void>` instead of `FutureOr<R>`
I figured out that there is an override on documentation:
```
  @protected
  @visibleForTesting
  FutureOr<R> onError<R>(DataException e) => throw e;
```
How can I override `sendRequest`  onError to returns onError<R> instead of void?

**Comment by frank06** [comment]
How are you using the `onError` function? Which part of your code is consuming it?

I changed this because I coudn't find a reason not to return `void`.

**Comment by frank06** [comment]
Making it `FutureOr<R>` would mean that the following:

```dart
    await familyRepository.save(family, onError: (e) async {
      notifier.updateWith(exception: e.error, stackTrace: e.stackTrace);
    });
```

would show a warning as the closure does not return a `Family`. And it doesn't make sense to return a `Family`.

Can you show me an example where it does make sense to return from `onError`? @rubgithub

**Comment by rubgithub** [comment]
Functional Programming

```
Future<Either<ErrorNotification, List<ClientModel>>> findClient({
    @required String clienteId,
  }) async {
    final Either<ErrorNotification, List<ClientModel>> _ret = await sendRequest(
      hostUri(
          baseUrl: baseUrl,
          pathRequest: 'api/clients/$clienteId'),
      method: DataRequestMethod.GET,
      onSuccess: (data) {
        final _ret = data as List<dynamic>;

        return right(_ret.map(
          (e) {
            final client = Map<String, dynamic>.from(e as Map<String, dynamic>);
            return client;
          },
        ).toList());
      },
      onError: (DataException e) {
        return left(e.error as ErrorNotification);
      },
    );

    return _ret.fold(
      (l) => left(l),
      (r) => right(r),
    );
}
```

**Comment by frank06** [comment]
Alright. That makes sense. I wonder are you using any of the higher level APIs like `watchOne`, `watchAll`?

Added a type param on `sendRequest` so we can both be happy.

https://github.com/flutterdata/flutter_data/commit/b6d501cbbb218c16a6d903f69ea108c1738e8aa3

That said, if I find this challenging when porting to null safety, I might remove it again.

Same goes for the provider and get_it codegen: will stay for now but if they become a nuisance I'll remove them (and add a note on the documentation on how to create a custom extension to support them both on user-land)

**Comment by rubgithub** [comment]
> Alright. That makes sense. I wonder are you using any of the higher level APIs like watchOne, watchAll?

No, I don't

> Added a type param on sendRequest so we can both be happy.
> That said, if I find this challenging when porting to null safety, I might remove it again.

Thank you, that give me some time to adapt my code.


> Same goes for the provider and get_it codegen: will stay for now but if they become a nuisance I'll remove them (and add a note on the documentation on how to create a custom extension to support them both on user-land)

Appreciate that, thank you.
