### ISSUE TITLE
null-safety support

### ISSUE THREAD

**Issue by frank06** [flutterdata/flutter_data#90]

**Comment by frank06** [comment]
wip

**Comment by ArneSaknussemm89** [comment]
Looking forward to null safety, definitely excited to try using this on my next project.

**Comment by frank06** [comment]
@ArneSaknussemm89 almost there! https://github.com/flutterdata/flutter_data/tree/null-safety

Tomorrow or in the next few days.

Next up... DOCS!

**Comment by frank06** [comment]
https://github.com/flutterdata/flutter_data/commit/3ba9aacd6984495fdacf11cd107556df9f938b92

**Comment by frank06** [comment]
You can try out `0.8.0-rc1` if you feel brave

**Comment by frank06** [comment]
Just ported https://github.com/flutterdata/flutter_data_todos to it, with no major issues. Seems to work well.

**Comment by glapworth** [comment]
Excellent work, thank you :)

**Comment by rubgithub** [comment]
> You can try out `0.8.0-rc1` if you feel brave

💪
