### ISSUE TITLE
replace hive local backend with isar?

### ISSUE THREAD

**Issue by frank06** [flutterdata/flutter_data#93]
https://github.com/isar/isar

**Comment by rubgithub** [comment]
Very interesting project, very useful to large data.
Any plans to this replacement?

**Comment by frank06** [comment]
Looks far from stable right now. Might revisit if there's enough incentive.

**Comment by frank06** [comment]
Using Isar might also help with a multi-isolate FD setup?

**Comment by huang12zheng** [comment]
I recommend isar by default, but if the user wants to use a HiveLocalAdapter, it is also supported
> Although I didn't use isar

**Comment by aexei** [comment]
Wie sieht hier der aktuelle Stand aus?

**Comment by frank06** [comment]
@aexei It's on hold

**Comment by aexei** [comment]
Oh ok. Why did you set it to on hold?

**Comment by frank06** [comment]
No time

**Comment by frank06** [comment]
https://github.com/flutterdata/yacht

**Comment by frank06** [comment]
Working on #223
