### ISSUE TITLE
Dependency on DataStateNotifier confusion

### ISSUE THREAD

**Issue by andreacioni** [flutterdata/flutter_data#95]
Hi Frank,

I saw lot of work is going on here and so I wanted to try a new version of this package. I upgraded from `0.5.17` to `0.6.3` and I'm facing this issue here:

![immagine](https://user-images.githubusercontent.com/7473284/113422497-1e3fab80-93cd-11eb-95ed-2040121a9b69.png)

Where the red line under _notifier_ say that:

```
The argument type 'DataStateNotifier<T> Function() (where DataStateNotifier is defined in /Users/andreacioni/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_data-0.6.3/lib/src/utils/data_state.dart)' can't be assigned to the parameter type 'DataStateNotifier<T> Function() (where DataStateNotifier is defined in /Users/andreacioni/flutter/.pub-cache/hosted/pub.dartlang.org/data_state-0.3.7/lib/data_state.dart)'.dartargument_type_not_assignable
data_state.dart(18, 4): DataStateNotifier is defined in /Users/andreacioni/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_data-0.6.3/lib/src/utils/data_state.dart
data_state.dart(15, 13): DataStateNotifier is defined in /Users/andreacioni/flutter/.pub-cache/hosted/pub.dartlang.org/data_state-0.3.7/lib/data_state.dart
```

It seems that there is some confusion between dependency DataStateNotifier from **flutter_data** and **data_state** (which I guess it's a transitive dependency of **flutter_data_state-0.3.1**)

I tried:
 - to upgrade to `0.7.0-rc6` -> this errors remains along with some new ones related to provider auto generation (I've not investigated too much because I read you are not supporting it any more)
 - to hide DataStateNotifier from flutter_data -> missing import, it cannot see DataStateNotifier from `flutter_data_state`
 - remove `flutter_data_state` dependency -> `DataStateWidgetBuilder`, `DataStateBuilder` are undefined

Could you give me an advise of what I'm missing? Is `flutter_data_state` a required dependency or it is deprecated?

Thank you in advance!

**Comment by frank06** [comment]
Hi @andreacioni, my apologies for the confusion. `DataState` has been incorporated in the latest releases of FD and the `flutter_data_state` will be deprecated.  I am about to release `0.7.0` (early next week) along with the new documentation site which will make everything clear again.

Riverpod is the easiest way of getting it running. Do you use Provider?

I recommend you check out https://github.com/flutterdata/flutter_data_setup_app (includes a sample extension for Provider) and https://github.com/flutterdata/flutter_data_todos which have been recently updated.

**Comment by andreacioni** [comment]
Yeah I'm on Provider since my project begun so right now I'm just studying Riverpod and planning how to migrate. By now I'll stay on Provider and I'll use the example you provided, thanks.

Looking forward to see new docs & features! 😃
