### ISSUE TITLE
Failed assertion: boolean expression must not be null

### ISSUE THREAD

**Issue by rubgithub** [flutterdata/flutter_data#96]
> Failed assertion: boolean expression must not be null
> [SEVERE] flutter_data:data_repository_builder on lib/mypath/user_model.dart  (cached)::

`sdk: ">=2.11.0 <3.0.0"`

My `build_runner` process is failing, I believe that was because I ran `dart migrate --skip-import-check`
Do you have some advice how to solve it? 

Thanks

**Comment by frank06** [comment]
Are you trying to migrate to null-safety?

**Comment by rubgithub** [comment]
I was trying to, 
Running dart `migrate --skip-import-check`  
Changing `sdk target`
But I rollback and now I'm getting this error

**Comment by frank06** [comment]
Please follow #90 for developments on null safety. I will start that in about 2 weeks.
