### ISSUE TITLE
Update Analyzer dependency to 0.40 to support latest auto_route

### ISSUE THREAD

**Issue by danielnordh** [flutterdata/flutter_data#99]
Flutter_data is 0.7 is incompatible with auto_route_generator 0.10 due to different analyzer version dependencies.

`Because auto_route_generator >=0.6.10 depends on analyzer >=0.40.0 <2.0.0 and flutter_data >=0.5.13 depends on analyzer ^0.39.5, auto_route_generator >=0.6.10 is incompatible with flutter_data >=0.5.13.`

**Comment by frank06** [comment]
I don't think I can upgrade the analyzer until moving to null safety, which I'm working on.

You could try with overriding dependencies like

```
dependency_overrides:
  analyzer: ^0.39.4
```

**Comment by frank06** [comment]
Working on `0.8.0` these days (`0.8.0-rc1` is out now), this issue will most likely be fixed. Let me know if not!
